import { describe, it, expect, beforeEach } from "vitest";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const SCRIPTS = join(__dirname, "..", "resources", "octobots-pack", "skill", "mission-planner", "scripts");
function run(script: string, args: string[], cwd: string): { out: string; code: number } {
  const result = spawnSync("node", [join(SCRIPTS, script), ...args], { cwd, encoding: "utf8" });
  const out = `${result.stdout ?? ""}${result.stderr ?? ""}`;
  const code = result.status ?? 1;
  return { out, code };
}

let repo: string;
let missionMd: string;
const GOOD =
  "# M\n\n## Description\nd\n\n## Acceptance Criteria\n- [ ] one\n- [x] two\n\n## Sessions\n_(no execution sessions yet)_\n\n" +
  "<!-- Auto-generated by Octobots ... -->\n## Tasks\n- Existing task\n";

beforeEach(() => {
  repo = mkdtempSync(join(tmpdir(), "octobots-scripts-"));
  missionMd = join(repo, ".octobots", "campaigns", "c", "missions", "m", "mission.md");
  mkdirSync(join(repo, ".octobots", "campaigns", "c", "missions", "m"), { recursive: true });
  writeFileSync(missionMd, GOOD, "utf8");
});

describe("validate.js", () => {
  it("passes a well-formed board (exit 0)", () => {
    expect(run("validate.js", [missionMd], repo).code).toBe(0);
  });
  it("fails a board missing the Octobots boundary comment (exit non-zero)", () => {
    writeFileSync(missionMd, "# M\n## Tasks\n- x\n", "utf8");
    const r = run("validate.js", [missionMd], repo);
    expect(r.code).not.toBe(0);
    expect(r.out.toLowerCase()).toContain("auto-generated");
  });

  it("rejects a placeholder task title like 'T1' (exit 1)", () => {
    const taskMd = join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "t1", "task.md");
    mkdirSync(join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "t1"), { recursive: true });
    writeFileSync(taskMd, "# T1\n\n## Acceptance Criteria\n- [ ] does the thing\n\n<!-- Auto-generated by Octobots ... -->\n## Tasks\n_(none)_\n", "utf8");
    const r = run("validate.js", [taskMd], repo);
    expect(r.code).toBe(1);
    expect(r.out.toLowerCase()).toContain("placeholder");
  });

  it("rejects a task with no acceptance criteria (exit 1)", () => {
    const taskMd = join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "wire-auth", "task.md");
    mkdirSync(join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "wire-auth"), { recursive: true });
    writeFileSync(taskMd, "# Wire up auth\n\n## Acceptance Criteria\n_(not set)_\n\n<!-- Auto-generated by Octobots ... -->\n## Tasks\n_(none)_\n", "utf8");
    const r = run("validate.js", [taskMd], repo);
    expect(r.code).toBe(1);
    expect(r.out.toLowerCase()).toContain("acceptance criteria");
  });

  it("passes a well-formed task (descriptive name + acceptance criterion)", () => {
    const taskMd = join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "wire-auth", "task.md");
    mkdirSync(join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "wire-auth"), { recursive: true });
    writeFileSync(taskMd, "# Add JWT validation to /login\n\n## Acceptance Criteria\n- [ ] rejects an expired token\n\n<!-- Auto-generated by Octobots ... -->\n## Tasks\n_(none)_\n", "utf8");
    expect(run("validate.js", [taskMd], repo).code).toBe(0);
  });

  it("flags a placeholder-named task in a mission's ## Tasks block", () => {
    writeFileSync(missionMd, GOOD.replace("- Existing task", "- Existing task\n- T5.5"), "utf8");
    const r = run("validate.js", [missionMd], repo);
    expect(r.code).toBe(1);
    expect(r.out).toContain("T5.5");
  });

  it("accepts the `<id> - name` title format (id prefix + descriptive name)", () => {
    const taskMd = join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "t31", "task.md");
    mkdirSync(join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "t31"), { recursive: true });
    writeFileSync(taskMd, "# T3.1 - Add JWT validation to /login\n\n## Acceptance Criteria\n- [ ] rejects expired tokens\n\n<!-- Auto-generated by Octobots ... -->\n## Tasks\n_(none)_\n", "utf8");
    expect(run("validate.js", [taskMd], repo).code).toBe(0);
    // And an `<id> - name` line inside a mission's ## Tasks is not flagged.
    writeFileSync(missionMd, GOOD.replace("- Existing task", "- T1.1 - Wire the API client"), "utf8");
    expect(run("validate.js", [missionMd], repo).code).toBe(0);
  });
});

describe("add-doc.js", () => {
  const WITH_DOCS =
    "# C\n\n## Description\nd\n\n## Acceptance Criteria\n- [ ] one\n\n## Documents\n_(none)_\n\n## Sessions\n_(no execution sessions yet)_\n\n" +
    "<!-- Auto-generated by Octobots ... -->\n## Missions\n- A mission\n";
  let campaignMd: string;
  beforeEach(() => {
    campaignMd = join(repo, ".octobots", "campaigns", "c", "campaign.md");
    writeFileSync(campaignMd, WITH_DOCS, "utf8");
  });

  it("replaces the _(none)_ placeholder with a `- [label](target)` link line", () => {
    const r = run("add-doc.js", [campaignMd, "M1 spec", "docs/superpowers/specs/foo.md"], repo);
    expect(r.code).toBe(0);
    const text = readFileSync(campaignMd, "utf8");
    expect(text).toContain("- [M1 spec](docs/superpowers/specs/foo.md)");
    expect(text).not.toContain("_(none)_");
    expect(text.indexOf("## Documents")).toBeLessThan(text.indexOf("## Sessions")); // stayed in its section
  });

  it("appends a second link without dropping the first", () => {
    run("add-doc.js", [campaignMd, "Spec", "docs/a.md"], repo);
    run("add-doc.js", [campaignMd, "Plan", "docs/b.md"], repo);
    const text = readFileSync(campaignMd, "utf8");
    expect(text).toContain("- [Spec](docs/a.md)");
    expect(text).toContain("- [Plan](docs/b.md)");
  });

  it("is idempotent on the target (no duplicate)", () => {
    run("add-doc.js", [campaignMd, "Spec", "docs/a.md"], repo);
    const r = run("add-doc.js", [campaignMd, "Renamed", "docs/a.md"], repo);
    expect(r.code).toBe(0);
    expect(r.out).toContain("already present");
    expect(readFileSync(campaignMd, "utf8").match(/docs\/a\.md/g)).toHaveLength(1);
  });

  it("errors when there is no ## Documents section (task boards)", () => {
    const r = run("add-doc.js", [missionMd, "X", "docs/x.md"], repo);
    expect(r.code).not.toBe(0);
    expect(r.out).toContain("Documents");
  });
});

describe("add-task.js", () => {
  it("appends a task under ## Tasks without touching the managed header", () => {
    const r = run("add-task.js", [missionMd, "Ship it"], repo);
    expect(r.code).toBe(0);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("- Existing task");
    expect(text).toContain("- Ship it");
    expect(text).toContain("Auto-generated by Octobots");
    expect(text.indexOf("## Description")).toBeLessThan(text.indexOf("## Tasks"));
  });
  it("replaces the empty placeholder line", () => {
    writeFileSync(missionMd, GOOD.replace("- Existing task", "_(none yet — the planner proposes tasks here)_"), "utf8");
    run("add-task.js", [missionMd, "First"], repo);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("- First");
    expect(text).not.toContain("_(none yet");
  });
  it("writes [role:<name>] marker when --role is provided", () => {
    const r = run("add-task.js", [missionMd, "Build API", "--role", "tech-lead"], repo);
    expect(r.code).toBe(0);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("- [role:tech-lead] Build API");
  });
  it("writes plain line (no role marker) when --role is absent", () => {
    const r = run("add-task.js", [missionMd, "Build UI"], repo);
    expect(r.code).toBe(0);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("- Build UI");
    expect(text).not.toContain("[role:");
  });
  it("--role flag replaces the empty placeholder with the role marker", () => {
    writeFileSync(missionMd, GOOD.replace("- Existing task", "_(none yet — the planner proposes tasks here)_"), "utf8");
    const r = run("add-task.js", ["--role", "backend", missionMd, "First task"], repo);
    expect(r.code).toBe(0);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("- [role:backend] First task");
    expect(text).not.toContain("_(none yet");
  });

  it("creates a folder-backed task: tasks/<slug>/task.md with a clean heading (no octobots:id marker)", () => {
    run("add-task.js", [missionMd, "Wire the auth flow", "--role", "tech-lead"], repo);
    const taskMd = join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "wire-the-auth-flow", "task.md");
    expect(existsSync(taskMd)).toBe(true);
    const md = readFileSync(taskMd, "utf8");
    // Clean heading — no octobots:id marker; entities are identified by folder path.
    expect(md).toMatch(/^# Wire the auth flow\n\n/);
    expect(md).not.toContain("octobots:id");
    expect(md).toContain("## Acceptance Criteria");
    expect(md).toContain("Auto-generated by Octobots");
  });
});

describe("add-bug.js", () => {
  it("appends a `- [severity:X] <title>` line under ## Bugs", () => {
    const r = run("add-bug.js", [missionMd, "Crash on save", "--severity", "critical"], repo);
    expect(r.code).toBe(0);
    expect(readFileSync(missionMd, "utf8")).toContain("- [severity:critical] Crash on save");
  });

  it("creates a folder-backed bug with a CLEAN slug + heading — no octobots:id marker", () => {
    // A title that previously corrupted slugs. The folder name and the bug.md `# heading` must stay
    // clean; markers belong only on the ## Bugs board line. No octobots:id is written.
    run("add-bug.js", [missionMd, "T6 - agent-creator is a SKILL not an agent", "--severity", "blocker"], repo);
    const bugsDir = join(repo, ".octobots", "campaigns", "c", "missions", "m", "bugs");
    const bugMd = readFileSync(join(bugsDir, "t6-agent-creator-is-a-skill-not-an-agent", "bug.md"), "utf8");
    // Clean heading — no octobots:id marker; entities are identified by folder path.
    expect(bugMd).toMatch(/^# T6 - agent-creator is a SKILL not an agent\n\n/);
    expect(bugMd).not.toContain("octobots:id");
    expect(bugMd).toContain("## Severity\nblocker");
    // No -2 duplicate folder (re-running the old auto-materialize used to spawn these).
    expect(existsSync(join(bugsDir, "t6-agent-creator-is-a-skill-not-an-agent-2"))).toBe(false);
  });
});

describe("set-criterion.js", () => {
  it("adds a criterion to ## Acceptance Criteria", () => {
    run("set-criterion.js", [missionMd, "add", "three"], repo);
    expect(readFileSync(missionMd, "utf8")).toContain("- [ ] three");
  });
  it("checks and unchecks by 1-based index", () => {
    run("set-criterion.js", [missionMd, "check", "1"], repo);
    expect(readFileSync(missionMd, "utf8")).toContain("- [x] one");
    run("set-criterion.js", [missionMd, "uncheck", "2"], repo);
    expect(readFileSync(missionMd, "utf8")).toContain("- [ ] two");
  });
});

describe("set-status.js", () => {
  it("sets a [status:done] marker on a matching task line", () => {
    const r = run("set-status.js", [missionMd, "Existing task", "done"], repo);
    expect(r.code).toBe(0);
    expect(readFileSync(missionMd, "utf8")).toContain("- [status:done] Existing task");
  });

  it("is idempotent: re-setting status replaces (does not duplicate) the marker", () => {
    run("set-status.js", [missionMd, "Existing task", "done"], repo);
    run("set-status.js", [missionMd, "Existing task", "active"], repo);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("- [status:active] Existing task");
    expect(text).not.toContain("[status:done]");
    expect(text.match(/\[status:/g)).toHaveLength(1);
  });

  it("preserves an existing [severity:] marker on a bug line and appends/updates [status:]", () => {
    writeFileSync(missionMd, GOOD + "\n## Bugs\n- [severity:blocker] Crash on save\n", "utf8");
    const r = run("set-status.js", [missionMd, "Crash on save", "done"], repo);
    expect(r.code).toBe(0);
    const text = readFileSync(missionMd, "utf8");
    expect(text).toContain("[severity:blocker]");
    expect(text).toContain("[status:done]");
    expect(text).toContain("Crash on save");
  });

  it("accepts a multi-word state like 'awaiting approval'", () => {
    const r = run("set-status.js", [missionMd, "Existing task", "awaiting", "approval"], repo);
    expect(r.code).toBe(0);
    expect(readFileSync(missionMd, "utf8")).toContain("- [status:awaiting approval] Existing task");
  });

  it("rejects an unknown state (exit 2)", () => {
    const r = run("set-status.js", [missionMd, "Existing task", "bogus"], repo);
    expect(r.code).toBe(2);
    expect(r.out.toLowerCase()).toContain("invalid state");
  });

  it("exits 1 when no board line matches the title", () => {
    const r = run("set-status.js", [missionMd, "No such task", "done"], repo);
    expect(r.code).toBe(1);
    expect(r.out.toLowerCase()).toContain("no board line");
  });

  it("exits 2 when args are missing", () => {
    const r = run("set-status.js", [missionMd, "Existing task"], repo);
    expect(r.code).toBe(2);
    expect(r.out.toLowerCase()).toContain("usage");
  });

  describe("campaign self-status (## Status section)", () => {
    let campaignMd: string;
    const CAMPAIGN =
      "# My Campaign\n<!-- octobots:id abc123 -->\n\n## Status\ndraft\n\n## Target\nt\n\n## Description\nd\n\n" +
      "<!-- Auto-generated by Octobots ... -->\n## Missions\n- A mission\n";
    beforeEach(() => {
      campaignMd = join(repo, ".octobots", "campaigns", "c", "campaign.md");
      writeFileSync(campaignMd, CAMPAIGN, "utf8");
    });

    it("replaces the campaign's ## Status body when the title matches the campaign heading", () => {
      const r = run("set-status.js", [campaignMd, "My Campaign", "done"], repo);
      expect(r.code).toBe(0);
      const text = readFileSync(campaignMd, "utf8");
      expect(text).toContain("## Status\ndone");
      expect(text).not.toContain("## Status\ndraft");
      // Other sections + tail are untouched.
      expect(text).toContain("## Target\nt");
      expect(text).toContain("## Missions");
      expect(text).toContain("- A mission");
    });

    it("inserts a ## Status section when one is absent (after the id marker)", () => {
      writeFileSync(
        campaignMd,
        "# My Campaign\n<!-- octobots:id abc123 -->\n\n## Target\nt\n\n<!-- Auto-generated by Octobots ... -->\n## Missions\n- A mission\n",
        "utf8",
      );
      const r = run("set-status.js", [campaignMd, "My Campaign", "cancelled"], repo);
      expect(r.code).toBe(0);
      const text = readFileSync(campaignMd, "utf8");
      expect(text).toContain("## Status\ncancelled");
      expect(text.indexOf("## Status")).toBeLessThan(text.indexOf("## Target"));
    });

    it("falls back to the board-line path when the title does NOT match the campaign name", () => {
      const r = run("set-status.js", [campaignMd, "A mission", "executing"], repo);
      expect(r.code).toBe(0);
      const text = readFileSync(campaignMd, "utf8");
      expect(text).toContain("- [status:executing] A mission");
      expect(text).toContain("## Status\ndraft"); // campaign's own status untouched
    });
  });
});

describe("list.js / show.js", () => {
  it("list.js prints the mission title from the tree", () => {
    const r = run("list.js", [], repo);
    expect(r.code).toBe(0);
    expect(r.out).toContain("M");
  });
  it("show.js --digest prints title and acceptance criteria", () => {
    const r = run("show.js", [missionMd, "--digest"], repo);
    expect(r.code).toBe(0);
    expect(r.out).toContain("M");
    expect(r.out).toContain("one");
  });
});

describe("create-team.js", () => {
  const baseArgs = [
    "--id", "team-web",
    "--title", "Web Team",
    "--backend", "claude",
    "--roster", "frontend,backend",
  ];

  it("creates a team marker with correct schema (no description)", () => {
    const r = run("create-team.js", baseArgs, repo);
    expect(r.code).toBe(0);
    expect(r.out).toContain("created team: team-web");

    const markerPath = join(repo, ".octobots", "teams", "team-web.json");
    const marker = JSON.parse(readFileSync(markerPath, "utf8"));
    expect(marker).toEqual({
      id: "team-web",
      title: "Web Team",
      backend: "claude",
      roster: ["frontend", "backend"],
    });
    expect(Object.prototype.hasOwnProperty.call(marker, "description")).toBe(false);
  });

  it("creates a team marker with description when --description provided", () => {
    const r = run("create-team.js", [...baseArgs, "--description", "Handles the web frontend"], repo);
    expect(r.code).toBe(0);

    const markerPath = join(repo, ".octobots", "teams", "team-web.json");
    const marker = JSON.parse(readFileSync(markerPath, "utf8"));
    expect(marker.description).toBe("Handles the web frontend");
    expect(marker.id).toBe("team-web");
    expect(marker.roster).toEqual(["frontend", "backend"]);
  });

  it("rejects an invalid --backend (exit 2)", () => {
    const r = run(
      "create-team.js",
      ["--id", "t", "--title", "T", "--backend", "openai", "--roster", "dev"],
      repo,
    );
    expect(r.code).toBe(2);
    expect(r.out.toLowerCase()).toContain("backend");
  });

  it("rejects a non-slug --id (exit 2)", () => {
    const r = run(
      "create-team.js",
      ["--id", "My Team!", "--title", "T", "--backend", "claude", "--roster", "dev"],
      repo,
    );
    expect(r.code).toBe(2);
    expect(r.out.toLowerCase()).toContain("id");
  });

  it("rejects an empty --roster (exit 2)", () => {
    const r = run(
      "create-team.js",
      ["--id", "t", "--title", "T", "--backend", "claude", "--roster", ""],
      repo,
    );
    expect(r.code).toBe(2);
    expect(r.out.toLowerCase()).toContain("roster");
  });

  it("refuses to overwrite an existing marker without --force (exit 1)", () => {
    run("create-team.js", baseArgs, repo);
    const r = run("create-team.js", baseArgs, repo);
    expect(r.code).toBe(1);
    expect(r.out).toContain("already exists");
    expect(r.out).toContain("--force");
  });

  it("overwrites an existing marker with --force (exit 0)", () => {
    run("create-team.js", baseArgs, repo);
    const r = run("create-team.js", [...baseArgs, "--title", "Web Team v2", "--force"], repo);
    expect(r.code).toBe(0);

    const markerPath = join(repo, ".octobots", "teams", "team-web.json");
    const marker = JSON.parse(readFileSync(markerPath, "utf8"));
    expect(marker.title).toBe("Web Team v2");
  });

  it("warns about an uninstalled role but still writes the marker (exit 0)", () => {
    const r = run(
      "create-team.js",
      ["--id", "team-ops", "--title", "Ops", "--backend", "copilot", "--roster", "ghost-role"],
      repo,
    );
    expect(r.code).toBe(0);
    expect(r.out.toLowerCase()).toContain("warning");
    expect(r.out.toLowerCase()).toContain("ghost-role");

    const markerPath = join(repo, ".octobots", "teams", "team-ops.json");
    const marker = JSON.parse(readFileSync(markerPath, "utf8"));
    expect(marker.roster).toEqual(["ghost-role"]);
  });

  it("does not warn about an installed role", () => {
    // simulate all roster roles installed as agent dirs
    mkdirSync(join(repo, ".claude", "agents", "frontend"), { recursive: true });
    mkdirSync(join(repo, ".claude", "agents", "backend"), { recursive: true });
    const r = run("create-team.js", baseArgs, repo);
    expect(r.code).toBe(0);
    expect(r.out).not.toContain("warning");
  });

  it("exits 2 when required args are missing", () => {
    const r = run("create-team.js", ["--id", "t"], repo);
    expect(r.code).toBe(2);
    expect(r.out.toLowerCase()).toContain("usage");
  });
});

describe("delete-bug.js", () => {
  it("removes the ## Bugs line AND trashes the bug folder", () => {
    const campaignMd = join(repo, ".octobots", "campaigns", "c", "campaign.md");
    const bugDir = join(repo, ".octobots", "campaigns", "c", "bugs", "boom");
    mkdirSync(bugDir, { recursive: true });
    writeFileSync(campaignMd, "# C\n\n<!-- Auto-generated by Octobots ... -->\n## Bugs\n- [status:done] Boom on save\n- Keep me\n", "utf8");
    writeFileSync(join(bugDir, "bug.md"), "# Boom on save\n\n## Severity\nmajor\n", "utf8");

    const r = run("delete-bug.js", [campaignMd, "Boom on save"], repo);
    expect(r.code).toBe(0);
    const md = readFileSync(campaignMd, "utf8");
    expect(md).not.toContain("Boom on save");
    expect(md).toContain("Keep me");
    expect(existsSync(bugDir)).toBe(false);
    expect(existsSync(join(repo, ".octobots", ".trash", "boom"))).toBe(true);
  });

  it("exits 1 when no matching bug exists", () => {
    const campaignMd = join(repo, ".octobots", "campaigns", "c", "campaign.md");
    writeFileSync(campaignMd, "# C\n\n<!-- Auto-generated by Octobots ... -->\n## Bugs\n- Other\n", "utf8");
    expect(run("delete-bug.js", [campaignMd, "Nope"], repo).code).toBe(1);
  });
});

describe("delete-task.js", () => {
  it("removes the ## Tasks block AND trashes the task folder", () => {
    const taskDir = join(repo, ".octobots", "campaigns", "c", "missions", "m", "tasks", "existing-task");
    mkdirSync(taskDir, { recursive: true });
    writeFileSync(join(taskDir, "task.md"), "# Existing task\n\n## Description\nd\n", "utf8");

    const r = run("delete-task.js", [missionMd, "Existing task"], repo);
    expect(r.code).toBe(0);
    expect(readFileSync(missionMd, "utf8")).not.toContain("Existing task");
    expect(existsSync(taskDir)).toBe(false);
    expect(existsSync(join(repo, ".octobots", ".trash", "existing-task"))).toBe(true);
  });
});
