import { describe, expect, it } from "vitest";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createCampaign, createMission, createTask } from "@octoshell/board";
import { readBoard } from "../src/board.js";
import { mkdtempClean } from "./fixtures/tmpdir.js";

/** A repo root with a `.octobots/` board — callers build the board tree via
 *  `@octoshell/board`'s own write API, never a hand-rolled YAML string, so
 *  the fixture stays honest about what a real board's `acceptance_criteria`
 *  round-trip actually produces. */
function repoWithBoard(): { root: string; octobotsDir: string } {
  const root = mkdtempClean("octograph-board-");
  const octobotsDir = join(root, ".octobots");
  mkdirSync(octobotsDir, { recursive: true });
  return { root, octobotsDir };
}

/**
 * A repo root with a LEGACY `.md` board — one campaign / mission / task, each
 * a managed-block brief, written verbatim rather than through the write API
 * (which only emits YAML now, so it cannot produce this generation at all).
 *
 * This is the generation `BoardModel` does NOT normalize: `readEntity`'s YAML
 * branch runs `renderCriteria` and emits machine-perfect `- [x] text`, but its
 * `.md` branch hands back `parseManagedBlock`'s `## Acceptance Criteria`
 * section body VERBATIM. Loose spacing and leading indentation are therefore
 * the AUTHORED form of a criterion here, not malformed input — which is the
 * whole reason `@octoshell/board`'s own `parseCriteriaString` is tolerant, and
 * the whole reason a stricter local copy of that rule is a defect rather than
 * a style choice.
 */
function repoWithLegacyMdBoard(criteriaBody: string): string {
  const root = mkdtempClean("octograph-board-md-");
  const taskDir = join(root, ".octobots", "campaigns", "c1", "missions", "m1", "tasks", "t1");
  mkdirSync(taskDir, { recursive: true });
  const brief = (kind: string, name: string, id: string, criteria: string): string =>
    [
      `# ${name}`,
      `<!-- octobots:id ${id} -->`,
      ``,
      `## Description`,
      `d`,
      ``,
      `## Acceptance Criteria`,
      criteria,
      `<!-- Auto-generated by Octobots from the ${kind}'s fields above. -->`,
      ``,
    ].join("\n");
  writeFileSync(join(root, ".octobots", "campaigns", "c1", "campaign.md"), brief("campaign", "Legacy Campaign", "C1", "- [ ] c"));
  writeFileSync(
    join(root, ".octobots", "campaigns", "c1", "missions", "m1", "mission.md"),
    brief("mission", "M1 - Legacy Mission", "M1", "- [ ] m"),
  );
  writeFileSync(join(taskDir, "task.md"), brief("task", "T1.1 - Legacy Task", "T1.1", criteriaBody));
  return root;
}

/** `readBoard`, asserting it found a board — never a `!` non-null assertion,
 *  which `eslint` bans package-wide (`@typescript-eslint/no-non-null-
 *  assertion`) precisely so a null case can't be silenced instead of tested. */
function requireBoard(root: string) {
  const board = readBoard(root);
  expect(board).not.toBeNull();
  if (board === null) throw new Error("unreachable: asserted above");
  return board;
}

describe("readBoard", () => {
  it("returns null for a repo with no .octobots directory", () => {
    const root = mkdtempClean("octograph-noboard-");
    expect(readBoard(root)).toBeNull();
  });

  it("names the owning mission and campaign for a task, and recovers its criteria", () => {
    const { root, octobotsDir } = repoWithBoard();
    const campaign = createCampaign(octobotsDir, { name: "Q3 Rollout" });
    const mission = createMission(octobotsDir, campaign.id, { title: "M1 - Auth" });
    const task = createTask(octobotsDir, mission.id, {
      name: "T1.1 - JWT",
      acceptanceCriteria: "- [x] jwt validated\n- [ ] expired rejected",
    });

    const board = requireBoard(root);
    const found = board.tasks.find((t) => t.id === task.id);
    expect(found).toEqual({
      id: task.id,
      name: "T1.1 - JWT",
      mission: mission.id,
      campaign: campaign.id,
      criteria: ["jwt validated", "expired rejected"],
    });
    expect(board.missionOf(task.id)).toBe(mission.id);
  });

  it("returns null missionOf for an unknown task id", () => {
    const { root } = repoWithBoard();
    const board = requireBoard(root);
    expect(board.missionOf("T99.9")).toBeNull();
  });

  it("parses a checked item, an unchecked item, and an empty criteria block", () => {
    const { root, octobotsDir } = repoWithBoard();
    const campaign = createCampaign(octobotsDir, { name: "Q3" });
    const mission = createMission(octobotsDir, campaign.id, { title: "M1 - Empty" });
    const checked = createTask(octobotsDir, mission.id, {
      name: "T1.1 - Checked",
      acceptanceCriteria: "- [x] done thing",
    });
    const unchecked = createTask(octobotsDir, mission.id, {
      name: "T1.2 - Unchecked",
      acceptanceCriteria: "- [ ] pending thing",
    });
    const empty = createTask(octobotsDir, mission.id, { name: "T1.3 - Empty" });

    const board = requireBoard(root);
    expect(board.tasks.find((t) => t.id === checked.id)?.criteria).toEqual(["done thing"]);
    expect(board.tasks.find((t) => t.id === unchecked.id)?.criteria).toEqual(["pending thing"]);
    expect(board.tasks.find((t) => t.id === empty.id)?.criteria).toEqual([]);
  });

  /**
   * The regression this test exists for: `readBoard` open-coded its own
   * checklist regex (`/^-\s\[[ xX]\]\s(.*)$/`) instead of calling
   * `@octoshell/board`'s `parseCriteriaString`, and justified it in a comment
   * claiming `BoardModel` "already normalizes both [board generations] into
   * the same checklist string". It does not: only the YAML branch runs
   * `renderCriteria`; the legacy `.md` branch returns the authored section
   * body verbatim. Against the three criteria below, the strict local copy
   * recovered ONE — and reported the other two as simply absent, which is an
   * empty-criteria claim the file does not support and the exact defect class
   * (a claim outrunning its evidence) this campaign keeps shipping.
   *
   * Behavioural half of the guard; `conventions.test.ts` holds the structural
   * half, which is what stops a second copy of the rule coming back.
   */
  it("recovers loosely-spaced and indented criteria from a legacy .md board, not just the machine-rendered form", () => {
    const root = repoWithLegacyMdBoard(
      ["-  [x]  loose spacing", "  - [ ] leading indentation", "- [ ] machine-rendered form"].join("\n"),
    );

    const board = requireBoard(root);
    expect(board.tasks.map((t) => t.criteria)).toEqual([
      ["loose spacing", "leading indentation", "machine-rendered form"],
    ]);
  });

  it("orders tasks deterministically (campaign, mission, id) rather than disk-scan order", () => {
    const { root, octobotsDir } = repoWithBoard();
    const campaign = createCampaign(octobotsDir, { name: "Q3" });
    const mission = createMission(octobotsDir, campaign.id, { title: "M1 - Order" });
    // Create in reverse-alphabetical name order; the board must not depend
    // on creation/disk-scan order to answer deterministically. `BoardModel`'s
    // own `listTasks` is newest-FIRST by mtime, so the creation order below is
    // exactly the order `readBoard` would emit if it did not re-sort — which
    // makes the assertion on the resulting order, not merely on run-to-run
    // agreement, the thing that can actually fail.
    createTask(octobotsDir, mission.id, { name: "T1.9 - Zeta" });
    createTask(octobotsDir, mission.id, { name: "T1.1 - Alpha" });

    const board1 = requireBoard(root);
    const board2 = requireBoard(root);
    expect(board1.tasks.map((t) => t.name)).toEqual(["T1.1 - Alpha", "T1.9 - Zeta"]);
    expect(board1.tasks.map((t) => t.id)).toEqual(board2.tasks.map((t) => t.id));
  });
});
