export type EntityKind = "campaign" | "mission" | "task" | "bug" | "workflow";

/** Authored content owned by the `.md` brief (the DB only caches these). */
export interface ManagedFields {
  /**
   * Legacy stable id read from a `<!-- octobots:id <id> -->` marker for backward compatibility.
   * New files never have this field set; entities are identified by `folder:<relFolderPath>`.
   * Parsed by `parseManagedBlock` so existing marked files keep their id until the file is next
   * regenerated without the marker.
   */
  id?: string;
  name: string;
  description: string;
  acceptanceCriteria: string;
  target?: string; // campaign only
  status?: string; // campaign only (settable; overrides the mission rollup)
  severity?: string;
  stepsToReproduce?: string;
  expected?: string;
  actual?: string;
  rca?: string;
  environment?: string;
  /** workflow only — the raw body of the `## Runs` section. */
  runs?: string;
  /** Free-form appended prose (decisions, rationale, sign-offs). Markdown, preserved verbatim. */
  notes?: string;
}

const PLACEHOLDER = "_(not set)_";

/**
 * The canonical entity status values — the exact strings the DB columns and the XState mission
 * machine store. This is the single source of truth for the set; the webview imports it (or
 * replicates it) to populate the Status dropdowns. `mapBoardStatus` maps human vocabulary onto
 * these; `isEntityStatus` is the validation guard used by the runtime status setters.
 */
export const ENTITY_STATUSES = [
  "draft",
  "executing",
  "awaitingApproval",
  "done",
  "failed",
  "cancelled",
] as const;

export type EntityStatus = (typeof ENTITY_STATUSES)[number];

export function isEntityStatus(value: string): value is EntityStatus {
  return (ENTITY_STATUSES as readonly string[]).includes(value);
}

/**
 * Canonical entity status values — the strings the DB / XState machine store. Board lines may carry
 * a `[status:<state>]` marker (parsed alongside `[severity:]`/`[role:]`); the human-facing vocabulary
 * in SKILL.md (`active`, `awaiting approval`, …) maps onto these. Returns `null` for an unknown word
 * so callers can ignore a malformed marker rather than store garbage.
 */
export function mapBoardStatus(raw: string): string | null {
  const key = raw.trim().toLowerCase().replace(/[\s_-]+/g, " ");
  switch (key) {
    case "draft":
      return "draft";
    case "active":
    case "executing":
    case "in progress":
    case "running":
      return "executing";
    case "awaiting approval":
    case "awaitingapproval":
    case "awaiting":
      return "awaitingApproval";
    case "done":
    case "complete":
    case "completed":
      return "done";
    case "failed":
    case "fail":
      return "failed";
    case "cancelled":
    case "canceled":
      return "cancelled";
    default:
      return null;
  }
}

function section(label: string, value: string | undefined): string {
  const trimmed = (value ?? "").trim();
  return `## ${label}\n${trimmed ? trimmed : PLACEHOLDER}\n`;
}

/**
 * Render the MANAGED block: heading + authored sections (Target only for campaigns) + any
 * pre-rendered injected sections (## Documents, ## Exec Sessions) + the boundary comment.
 * `owner` names the agent that owns the tail appended below the comment (orchestrator/planner).
 * The caller appends the preserved planner-owned tail after this block.
 */
export function renderManagedBlock(
  kind: EntityKind,
  fields: ManagedFields,
  injectedSections: string[],
  owner: string,
): string {
  const lines = [`# ${fields.name}`];
  lines.push(``);
  if (kind === "workflow") {
    lines.push(section("Description", fields.description));
    lines.push(section("Runs", fields.runs ?? ""));
  } else if (kind === "bug") {
    lines.push(section("Severity", fields.severity ?? ""));
    lines.push(section("Description", fields.description));
    lines.push(section("Steps to Reproduce", fields.stepsToReproduce ?? ""));
    lines.push(section("Expected", fields.expected ?? ""));
    lines.push(section("Actual", fields.actual ?? ""));
    lines.push(section("RCA", fields.rca ?? ""));
    lines.push(section("Environment", fields.environment ?? ""));
  } else {
    if (kind === "campaign") {
      // Settable campaign status — round-trips to the DB and overrides the mission rollup when not
      // `draft`. Rendered first (right after the heading/id) so it is easy to find and edit.
      lines.push(section("Status", fields.status ?? "draft"));
      lines.push(section("Target", fields.target ?? ""));
    }
    lines.push(section("Description", fields.description));
    lines.push(section("Acceptance Criteria", fields.acceptanceCriteria));
  }
  for (const s of injectedSections) lines.push(s);
  lines.push(
    `<!-- Auto-generated by Octobots from the ${kind}'s fields above. The ${owner} owns any sections appended below this comment. -->`,
  );
  lines.push(``);
  return lines.join("\n");
}

/**
 * Parse authored fields from a brief's full text. The `#` heading is the name; each `## Section`
 * body runs until the next `## ` heading or the `<!--` boundary comment. A placeholder/empty body
 * parses to "" — an exact reflection of the file (the DB is no longer an authority to protect).
 * `target` is always returned; non-campaign callers ignore it.
 */
export function parseManagedBlock(text: string): ManagedFields {
  const heading = /^#\s+(.+?)\s*$/m.exec(text);
  const name = heading ? (heading[1] ?? "").trim() : "";
  const idMarker = /^<!--\s*octobots:id\s+(\S+)\s*-->/m.exec(text);
  const id = idMarker ? idMarker[1] : undefined;
  const sectionBody = (label: string): string => {
    const re = new RegExp(`^##\\s+${label}\\s*$`, "m");
    const mt = re.exec(text);
    if (!mt) return "";
    const rest = text.slice(mt.index + mt[0].length);
    const nextHeading = rest.search(/^##\s+/m);
    const comment = rest.search(/^<!--/m);
    const ends = [nextHeading, comment].filter((n) => n >= 0);
    const cut = ends.length ? Math.min(...ends) : -1;
    const body = (cut >= 0 ? rest.slice(0, cut) : rest).trim();
    return body === PLACEHOLDER ? "" : body;
  };
  return {
    ...(id ? { id } : {}),
    name,
    description: sectionBody("Description"),
    acceptanceCriteria: sectionBody("Acceptance Criteria"),
    target: sectionBody("Target"),
    status: sectionBody("Status"),
    severity: sectionBody("Severity"),
    stepsToReproduce: sectionBody("Steps to Reproduce"),
    expected: sectionBody("Expected"),
    actual: sectionBody("Actual"),
    rca: sectionBody("RCA"),
    environment: sectionBody("Environment"),
    runs: sectionBody("Runs"),
  };
}

/**
 * Parse the agent-driveable document **links** out of a brief's `## Documents` section so they can
 * round-trip into `link` resources. Only markdown-link lines (`- [label](target)`) are returned —
 * these are the form an agent (or `add-doc.js`) writes to attach a spec/plan. Plain `- name` lines
 * (folder files auto-listed by the app) and `- label (target)` lines (file resources) are ignored,
 * so reconciling against this never deletes a disk file or an attached file. Deduped by target,
 * first occurrence wins. Returns `[]` when there is no Documents section or it is the placeholder.
 */
export function parseDocumentLinks(text: string): { label: string; target: string }[] {
  const head = /^##\s+Documents\s*$/m.exec(text);
  if (!head) return [];
  const rest = text.slice(head.index + head[0].length);
  const nextHeading = rest.search(/^##\s+/m);
  const body = nextHeading >= 0 ? rest.slice(0, nextHeading) : rest;
  const out: { label: string; target: string }[] = [];
  const seen = new Set<string>();
  const line = /^\s*-\s+\[(.+?)\]\((.+?)\)\s*$/;
  for (const raw of body.split("\n")) {
    const m = line.exec(raw);
    if (!m) continue;
    const label = (m[1] ?? "").trim();
    const target = (m[2] ?? "").trim();
    if (!target || seen.has(target)) continue;
    seen.add(target);
    out.push({ label, target });
  }
  return out;
}

/**
 * The entity NAME carried by a `## Tasks` / `## Bugs` board line, given the line body with leading
 * `[key:value]` markers already stripped. Mirrors the planner's `name`/`description` rule so status
 * lookups key on the same name the entity is parsed with: strip a leading `[ ]` checkbox and `**bold**`
 * markers, then split off an inline `Title — desc` / `Title: desc` description. An ASCII-hyphen
 * `<id> - name` is preserved (only ` — `/` – ` em/en-dash and `: ` separate a description).
 */
export function boardLineEntityName(bareTitle: string): string {
  const cleaned = bareTitle.replace(/^\[[ xX]\]\s*/, "").replace(/\*\*/g, "").trim();
  const sep = cleaned.match(/\s+[—–]\s+|:\s+/);
  return sep ? cleaned.slice(0, sep.index).trim() : cleaned;
}
