import { readdirSync, readFileSync, statSync } from "node:fs";
import { basename, dirname, join, parse, relative, resolve, sep } from "node:path";
import type { EntityKind } from "./managed-block.js";
import { isCampaignDir } from "./board-model.js";
import { loadEntity, KIND_KEYS, KNOWN_KEYS, type EntityFields } from "./entity-schema.js";

export interface BoardFinding {
  mdPath: string;
  kind: EntityKind;
  /** "warning" findings are non-fatal: the board is still valid. */
  severity: "error" | "warning";
  message: string;
}

/**
 * A name is a placeholder if it's empty, a letter-prefixed sequence number,
 * a bare number, or a generic word. Ported verbatim from validate.js lines ~60-72.
 */
export function isPlaceholderName(raw: string): boolean {
  const s = (raw ?? "")
    .trim()
    .replace(/\*\*/g, "")
    .replace(/^\[[ xX]\]\s*/, "")
    .replace(/^\[(?:role|status|severity):[^\]]+\]\s*/i, "")
    .trim();
  if (!s) return true;
  if (/^[A-Za-z]{1,4}\d+(\.\d+)?$/.test(s)) return true; // T1, M3, T5.5, TSK12, C2
  if (/^\d+(\.\d+)?$/.test(s)) return true; // bare number
  if (/^(task|mission|campaign|bug|phase|step|item|untitled|tbd|todo|new\s+\w+)\s*\d*(\.\d+)?$/i.test(s)) return true;
  return false;
}

/** Body text of a `## <label>` section (until the next `## ` heading or the boundary comment). */
function sectionBody(text: string, label: string): string {
  const m = new RegExp(`^##\\s+${label}\\s*$`, "m").exec(text);
  if (!m) return "";
  const rest = text.slice(m.index + m[0].length);
  const ends = [rest.search(/^##\s+/m), rest.search(/^<!--/m)].filter((n) => n >= 0);
  return ends.length ? rest.slice(0, Math.min(...ends)) : rest;
}

function hasAcceptanceCriterion(text: string): boolean {
  return /^\s*-\s*\[[ xX]\]\s*\S/m.test(sectionBody(text, "Acceptance Criteria"));
}

/** Top-level (column-0) item titles under `## Tasks`. */
function taskNames(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => /^##\s+Tasks\s*$/.test((l ?? "").trim()));
  if (start < 0) return [];
  const out: string[] = [];
  for (let i = start + 1; i < lines.length; i++) {
    const raw = lines[i] ?? "";
    if (/^##\s+/.test(raw.trim())) break;
    const mLine = raw.match(/^(?:\d+[.)]\s+|[-*]\s+)(.*)$/);
    if (mLine) out.push(mLine[1] ?? "");
  }
  return out;
}

/**
 * Validate a single brief's text. Pure and testable on a string.
 * Applies rules 1-5 from validate.js by kind.
 */
export function validateBriefText(kind: EntityKind, text: string, mdPath: string): BoardFinding[] {
  const findings: BoardFinding[] = [];
  const push = (message: string) => findings.push({ mdPath, kind, severity: "error", message });

  // Rule 1: title present and not a placeholder
  const titleM = /^#\s+(.+?)\s*$/m.exec(text);
  if (!titleM) {
    push("missing a `# Title` heading");
  } else {
    const title = (titleM[1] ?? "").trim();
    if (isPlaceholderName(title)) {
      push(
        `title "${title}" is just an id/placeholder — use the form \`<id> - descriptive name\` ` +
          `(e.g. "M3 - Skills workspace", "T3.1 - Add JWT validation to /login"); the bare id alone is not a name`,
      );
    }
  }

  // Rule 2: boundary comment present
  if (!text.includes("Auto-generated by Octobots") && !text.includes("Auto-generated by Octoshell")) {
    push("missing the `Auto-generated by Octobots` boundary comment");
  }

  // Rule 3: an agent-owned section present
  if (!/^##\s+(Tasks|Missions|Bugs)\s*$/m.test(text)) {
    push("missing an agent-owned `## Tasks`, `## Missions`, or `## Bugs` section");
  }

  // Rule 4: missions and tasks must carry at least one verifiable acceptance criterion
  if ((kind === "mission" || kind === "task") && !hasAcceptanceCriterion(text)) {
    push(
      "no acceptance criterion — add at least one checkable `- [ ]` item under `## Acceptance Criteria` " +
        "(use set-criterion.js); a task/mission without a verifiable acceptance criterion is not well-formed",
    );
  }

  // Rule 5: a mission's ## Tasks items must not be bare ids
  if (kind === "mission") {
    for (const name of taskNames(text)) {
      if (isPlaceholderName(name)) {
        push(
          `task "${name.trim()}" is just an id — use \`<id> - descriptive name\` ` +
            `(e.g. "T3.1 - Add JWT validation to /login"), not a bare "T1"/"T5.5"`,
        );
      }
    }
  }

  return findings;
}

function safeReaddir(dir: string): string[] {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

function safeReadFile(filePath: string): string | null {
  try {
    return readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

/** Validate a parsed YAML entity: a descriptive name, and (mission/task) ≥1 acceptance criterion. */
function validateEntityYaml(kind: EntityKind, fields: EntityFields, path: string): BoardFinding[] {
  const findings: BoardFinding[] = [];
  const push = (message: string): void => {
    findings.push({ mdPath: path, kind, severity: "error", message });
  };
  if (!fields.name.trim()) {
    push("missing a name");
  } else if (isPlaceholderName(fields.name)) {
    push(
      `title "${fields.name.trim()}" is just an id/placeholder — use the form \`<id> - descriptive name\` ` +
        `(e.g. "M3 - Skills workspace", "T3.1 - Add JWT validation to /login"); the bare id alone is not a name`,
    );
  }
  if ((kind === "mission" || kind === "task") && !fields.acceptanceCriteria.some((c) => c.text.trim())) {
    push(
      "no acceptance criterion — add at least one checkable acceptance criterion (use set-criterion.js); " +
        "a task/mission without a verifiable acceptance criterion is not well-formed",
    );
  }
  // A key this schema knows but this kind does not own. It is preserved across writes (nothing is
  // silently deleted) but the board never reads it, so it is reported rather than left to rot.
  // `kind` here is the wider managed-block union; only the four YAML kinds have a key list.
  const owned: readonly string[] | undefined = KIND_KEYS[kind as keyof typeof KIND_KEYS];
  for (const key of owned ? Object.keys(fields.extra ?? {}) : []) {
    if (!KNOWN_KEYS.has(key) || owned!.includes(key)) continue;
    push(`\`${key}\` is not a ${kind} field (${owningKinds(key)}) — it is preserved on disk but the board ignores it`);
  }

  // Criteria appended as prose into `notes` instead of written to `acceptance_criteria`: they read
  // fine to a human but the board never sees them as criteria. Bugs carry no criteria, so a
  // checkbox in a bug's notes is a legitimate repro checklist.
  if (kind !== "bug") {
    const stranded = strandedCriteria(fields.notes);
    if (stranded.length) {
      push(
        `${stranded.length} acceptance criterion-shaped line(s) stranded in \`notes\` ` +
          `(first: "${stranded[0]}") — notes are free-form prose the board never reads as criteria; ` +
          "move them into `acceptance_criteria` with set-criterion.js and never append them by hand",
      );
    }
  }
  return findings;
}

/** Human-readable list of the kinds that DO own `key`, for the misplaced-field message. */
function owningKinds(key: string): string {
  const kinds = (Object.keys(KIND_KEYS) as Array<keyof typeof KIND_KEYS>).filter((k) => KIND_KEYS[k].includes(key));
  return kinds.length ? `${kinds.join("/")} only` : "no kind uses it";
}

/**
 * Checkbox lines sitting in an entity's free-form `notes` — acceptance criteria that were appended
 * as text instead of written through the parser. Returns their texts.
 * Mirrors the pack's `scripts/validate.js` `strandedCriteria` — keep the two in step.
 */
export function strandedCriteria(notes: string | undefined): string[] {
  const out: string[] = [];
  for (const line of (notes ?? "").split("\n")) {
    const m = line.match(/^\s*[-*]\s*\[[ xX]\]\s*(\S.*)$/);
    if (m) out.push((m[1] ?? "").trim());
  }
  return out;
}

/** Validate one entity, preferring its `<kind>.yaml` and falling back to a legacy `<kind>.md`. */
function validateFile(filePath: string, kind: EntityKind): BoardFinding[] {
  const yamlPath = filePath.replace(/\.md$/, ".yaml");
  const yamlText = safeReadFile(yamlPath);
  if (yamlText !== null) return validateEntityYaml(kind, loadEntity(yamlText), yamlPath);
  const text = safeReadFile(filePath);
  if (text === null) return [];
  return validateBriefText(kind, text, filePath);
}

// ── Leftover `workflows/` folders ───────────────────────────────────────────
// Workflow support was removed in pack v57: the board model ignores `workflows/` and no script reads
// it. The folders are the user's data, so they are only ever REPORTED, as warnings — never touched.
//
// DUAL IMPLEMENTATION: this is the TypeScript spelling of the pack's
// `resources/octobots-pack/skill/mission-planner/scripts/legacy-workflows.mjs` (the pack script
// stays dependency-free, so it cannot import this). The message text and the rule must stay equal;
// `test/validate-workflows-warning.test.ts` runs both over a real board copy.

const NO_LONGER_READ = "no longer read since pack v57";

const isDir = (p: string): boolean => {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
};

/**
 * The board root (the folder holding `campaigns/`) that `dir` sits in: the nearest `.octobots`
 * ancestor, else the parent of the nearest `campaigns` ancestor (a board copied to a folder with
 * another name), else `dir` itself. Mirrors `boardRootOf` in legacy-workflows.mjs.
 */
function boardRootOf(dir: string): string {
  const start = resolve(dir);
  for (let d = start; d !== parse(d).root; d = dirname(d)) if (basename(d) === ".octobots") return d;
  for (let d = start; d !== parse(d).root; d = dirname(d)) if (basename(d) === "campaigns") return dirname(d);
  return start;
}

/** The directory holding `campaigns/` for a validateBoard root: `<root>/.octobots`, else `root`. */
function boardDirOf(root: string): string {
  const nested = join(root, ".octobots");
  return isDir(nested) ? nested : root;
}

/**
 * One warning per leftover `workflows/<slug>/` folder directly under the campaign or mission folder
 * `dir`; a `workflows/` holding no sub-folder is one finding for itself. `message` is the part of
 * validate.js's `warning:` line after the prefix: `<rel>: no longer read since pack v57`, with `rel`
 * relative to the board root and `/`-separated.
 */
function legacyWorkflowFindings(dir: string, kind: "campaign" | "mission"): BoardFinding[] {
  const w = join(dir, "workflows");
  if (!isDir(w)) return [];
  const slugs = readdirSync(w, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => join(w, e.name));
  const base = boardRootOf(dir);
  return (slugs.length ? slugs : [w]).map((folder) => ({
    mdPath: folder,
    kind,
    severity: "warning" as const,
    message: `${relative(base, folder).split(sep).join("/")}: ${NO_LONGER_READ}`,
  }));
}

/**
 * Walk every entity under the board and aggregate findings. `root` is a workspace holding
 * `.octobots/`, or the board directory itself (the folder holding `campaigns/`, whatever it is named).
 * Covers:
 *   campaigns/<id>/campaign.md
 *   campaigns/<id>/missions/<id>/mission.md
 *   campaigns/<id>/missions/<id>/tasks/<id>/task.md
 *   campaigns/<id>/missions/<id>/bugs/<id>/bug.md
 *   campaigns/<id>/bugs/<id>/bug.md
 */

export function validateBoard(root: string): BoardFinding[] {
  const findings: BoardFinding[] = [];
  const campaigns = join(boardDirOf(root), "campaigns");

  for (const campaignId of safeReaddir(campaigns)) {
    const campaignDir = join(campaigns, campaignId);

    // campaign.md
    findings.push(...validateFile(join(campaignDir, "campaign.md"), "campaign"));
    // only a real campaign (campaign.yaml/.md, the BoardModel rule) has workflows/ worth reporting
    if (isCampaignDir(campaignDir)) {
      findings.push(...legacyWorkflowFindings(campaignDir, "campaign"));
    }

    // campaign-level bugs
    const campaignBugs = join(campaignDir, "bugs");
    for (const bugId of safeReaddir(campaignBugs)) {
      findings.push(...validateFile(join(campaignBugs, bugId, "bug.md"), "bug"));
    }

    // missions
    const missionsDir = join(campaignDir, "missions");
    for (const missionId of safeReaddir(missionsDir)) {
      const missionDir = join(missionsDir, missionId);

      // mission.md
      findings.push(...validateFile(join(missionDir, "mission.md"), "mission"));
      if (isCampaignDir(campaignDir)) findings.push(...legacyWorkflowFindings(missionDir, "mission"));

      // mission tasks
      const tasksDir = join(missionDir, "tasks");
      for (const taskId of safeReaddir(tasksDir)) {
        findings.push(...validateFile(join(tasksDir, taskId, "task.md"), "task"));
      }

      // mission-level bugs
      const missionBugs = join(missionDir, "bugs");
      for (const bugId of safeReaddir(missionBugs)) {
        findings.push(...validateFile(join(missionBugs, bugId, "bug.md"), "bug"));
      }
    }
  }

  return findings;
}
