import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { EntityKind } from "./managed-block.js";
import { parseWorkflowMeta } from "./workflow-meta.js";

export interface BoardFinding {
  mdPath: string;
  kind: EntityKind;
  severity: "error";
  message: string;
}

/**
 * A name is a placeholder if it's empty, a letter-prefixed sequence number,
 * a bare number, or a generic word. Ported verbatim from validate.js lines ~60-72.
 */
export function isPlaceholderName(raw: string): boolean {
  const s = (raw ?? "")
    .trim()
    .replace(/\*\*/g, "")
    .replace(/^\[[ xX]\]\s*/, "")
    .replace(/^\[(?:role|status|severity):[^\]]+\]\s*/i, "")
    .trim();
  if (!s) return true;
  if (/^[A-Za-z]{1,4}\d+(\.\d+)?$/.test(s)) return true; // T1, M3, T5.5, TSK12, C2
  if (/^\d+(\.\d+)?$/.test(s)) return true; // bare number
  if (/^(task|mission|campaign|bug|phase|step|item|untitled|tbd|todo|new\s+\w+)\s*\d*(\.\d+)?$/i.test(s)) return true;
  return false;
}

/** Body text of a `## <label>` section (until the next `## ` heading or the boundary comment). */
function sectionBody(text: string, label: string): string {
  const m = new RegExp(`^##\\s+${label}\\s*$`, "m").exec(text);
  if (!m) return "";
  const rest = text.slice(m.index + m[0].length);
  const ends = [rest.search(/^##\s+/m), rest.search(/^<!--/m)].filter((n) => n >= 0);
  return ends.length ? rest.slice(0, Math.min(...ends)) : rest;
}

function hasAcceptanceCriterion(text: string): boolean {
  return /^\s*-\s*\[[ xX]\]\s*\S/m.test(sectionBody(text, "Acceptance Criteria"));
}

/** Top-level (column-0) item titles under `## Tasks`. */
function taskNames(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => /^##\s+Tasks\s*$/.test((l ?? "").trim()));
  if (start < 0) return [];
  const out: string[] = [];
  for (let i = start + 1; i < lines.length; i++) {
    const raw = lines[i] ?? "";
    if (/^##\s+/.test(raw.trim())) break;
    const mLine = raw.match(/^(?:\d+[.)]\s+|[-*]\s+)(.*)$/);
    if (mLine) out.push(mLine[1] ?? "");
  }
  return out;
}

/**
 * Validate a single brief's text. Pure and testable on a string.
 * Applies rules 1-5 from validate.js by kind.
 */
export function validateBriefText(kind: EntityKind, text: string, mdPath: string): BoardFinding[] {
  const findings: BoardFinding[] = [];
  const push = (message: string) => findings.push({ mdPath, kind, severity: "error", message });

  // Rule 1: title present and not a placeholder
  const titleM = /^#\s+(.+?)\s*$/m.exec(text);
  if (!titleM) {
    push("missing a `# Title` heading");
  } else {
    const title = (titleM[1] ?? "").trim();
    if (isPlaceholderName(title)) {
      push(
        `title "${title}" is just an id/placeholder — use the form \`<id> - descriptive name\` ` +
          `(e.g. "M3 - Skills workspace", "T3.1 - Add JWT validation to /login"); the bare id alone is not a name`,
      );
    }
  }

  // Rule 2: boundary comment present
  if (!text.includes("Auto-generated by Octobots") && !text.includes("Auto-generated by Octoshell")) {
    push("missing the `Auto-generated by Octobots` boundary comment");
  }

  // Rule 3: an agent-owned section present
  if (!/^##\s+(Tasks|Missions|Bugs)\s*$/m.test(text)) {
    push("missing an agent-owned `## Tasks`, `## Missions`, or `## Bugs` section");
  }

  // Rule 4: missions and tasks must carry at least one verifiable acceptance criterion
  if ((kind === "mission" || kind === "task") && !hasAcceptanceCriterion(text)) {
    push(
      "no acceptance criterion — add at least one checkable `- [ ]` item under `## Acceptance Criteria` " +
        "(use set-criterion.js); a task/mission without a verifiable acceptance criterion is not well-formed",
    );
  }

  // Rule 5: a mission's ## Tasks items must not be bare ids
  if (kind === "mission") {
    for (const name of taskNames(text)) {
      if (isPlaceholderName(name)) {
        push(
          `task "${name.trim()}" is just an id — use \`<id> - descriptive name\` ` +
            `(e.g. "T3.1 - Add JWT validation to /login"), not a bare "T1"/"T5.5"`,
        );
      }
    }
  }

  return findings;
}

function safeReaddir(dir: string): string[] {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

function safeReadFile(filePath: string): string | null {
  try {
    return readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

function validateFile(filePath: string, kind: EntityKind): BoardFinding[] {
  const text = safeReadFile(filePath);
  if (text === null) return [];
  return validateBriefText(kind, text, filePath);
}

/**
 * Walk every .md under .octobots/ and aggregate findings.
 * Covers:
 *   campaigns/<id>/campaign.md
 *   campaigns/<id>/missions/<id>/mission.md
 *   campaigns/<id>/missions/<id>/tasks/<id>/task.md
 *   campaigns/<id>/missions/<id>/bugs/<id>/bug.md
 *   campaigns/<id>/bugs/<id>/bug.md
 */
/**
 * Validate one workflow folder. `mdPath` is used as the finding location because it is the file a
 * human opens; script problems are reported against it too so every finding has one anchor.
 */
export function validateWorkflow(mdPath: string, jsPath: string, folderSlug: string): BoardFinding[] {
  const out: BoardFinding[] = [];
  const err = (message: string): void => {
    out.push({ mdPath, kind: "workflow", severity: "error", message });
  };

  if (!existsSync(jsPath)) {
    err("workflow.js is missing");
    return out;
  }

  let meta;
  try {
    meta = parseWorkflowMeta(readFileSync(jsPath, "utf8"));
  } catch (e) {
    err((e as Error).message);
    return out;
  }

  if (meta.name !== folderSlug) {
    err(`meta.name "${meta.name}" does not match its folder "${folderSlug}"`);
  }
  if (meta.phases.length === 0) {
    err("workflow has no phases");
    return out;
  }

  const stepPhase = new Map<string, number>();     // step id → phase index
  const parallelPhase = new Map<string, number>(); // parallel group → phase index

  meta.phases.forEach((phase, pi) => {
    if (phase.steps.length === 0) err(`phase "${phase.title}" has no steps`);
    for (const step of phase.steps) {
      if (stepPhase.has(step.id)) err(`duplicate step id "${step.id}"`);
      else stepPhase.set(step.id, pi);

      if (step.parallel !== undefined) {
        const seen = parallelPhase.get(step.parallel);
        if (seen !== undefined && seen !== pi) {
          err(`parallel group "${step.parallel}" spans more than one phase`);
        } else if (seen === undefined) {
          parallelPhase.set(step.parallel, pi);
        }
      }
    }
  });

  for (const phase of meta.phases) {
    for (const step of phase.steps) {
      for (const dep of step.dependsOn ?? []) {
        if (!stepPhase.has(dep)) err(`step "${step.id}" dependsOn "${dep}", which is not a step`);
      }
    }
  }

  return out;
}

/** Validate every workflow folder under an entity, returning the count found. */
function validateWorkflowsUnder(entityDir: string, findings: BoardFinding[]): number {
  const dir = join(entityDir, "workflows");
  const slugs = safeReaddir(dir);
  for (const slug of slugs) {
    findings.push(...validateWorkflow(join(dir, slug, "workflow.md"), join(dir, slug, "workflow.js"), slug));
  }
  return slugs.length;
}

export function validateBoard(root: string): BoardFinding[] {
  const findings: BoardFinding[] = [];
  const octobots = join(root, ".octobots");
  const campaigns = join(octobots, "campaigns");

  for (const campaignId of safeReaddir(campaigns)) {
    const campaignDir = join(campaigns, campaignId);

    // campaign.md
    findings.push(...validateFile(join(campaignDir, "campaign.md"), "campaign"));
    validateWorkflowsUnder(campaignDir, findings);

    // campaign-level bugs
    const campaignBugs = join(campaignDir, "bugs");
    for (const bugId of safeReaddir(campaignBugs)) {
      findings.push(...validateFile(join(campaignBugs, bugId, "bug.md"), "bug"));
    }

    // missions
    const missionsDir = join(campaignDir, "missions");
    for (const missionId of safeReaddir(missionsDir)) {
      const missionDir = join(missionsDir, missionId);

      // mission.md
      findings.push(...validateFile(join(missionDir, "mission.md"), "mission"));
      const missionWorkflows = validateWorkflowsUnder(missionDir, findings);
      if (missionWorkflows > 1) {
        findings.push({
          mdPath: join(missionDir, "mission.md"),
          kind: "mission",
          severity: "error",
          message: `mission has more than one workflow (${missionWorkflows}); a mission may have at most one`,
        });
      }

      // mission tasks
      const tasksDir = join(missionDir, "tasks");
      for (const taskId of safeReaddir(tasksDir)) {
        findings.push(...validateFile(join(tasksDir, taskId, "task.md"), "task"));
      }

      // mission-level bugs
      const missionBugs = join(missionDir, "bugs");
      for (const bugId of safeReaddir(missionBugs)) {
        findings.push(...validateFile(join(missionBugs, bugId, "bug.md"), "bug"));
      }
    }
  }

  return findings;
}
