import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { BoardModel } from "../src/board-model.js";
import { renderManagedBlock } from "../src/managed-block.js";

let root: string;
beforeEach(() => { root = mkdtempSync(join(tmpdir(), "board-")); });
afterEach(() => { rmSync(root, { recursive: true, force: true }); });

function writeBrief(kind: "campaign" | "mission" | "task" | "bug", dir: string, fields: Record<string, unknown>, tail = "") {
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${kind}.md`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  writeFileSync(file, renderManagedBlock(kind, fields as any, [], "planner") + tail, "utf8");
}

describe("BoardModel read API", () => {
  it("parses campaigns, missions, and tasks from disk (folder-path ids — no marker emitted)", () => {
    // Since renderManagedBlock no longer emits octobots:id, all ids are folder-based.
    const cDir = join(root, "campaigns", "q3");
    writeBrief("campaign", cDir, { name: "Q3", description: "", acceptanceCriteria: "", status: "draft", target: "" });
    const mDir = join(cDir, "missions", "m-skills");
    writeBrief("mission", mDir, { name: "M1 - Skills", description: "d", acceptanceCriteria: "- [ ] ac" });
    const tDir = join(mDir, "tasks", "t-jwt");
    writeBrief("task", tDir, { name: "T1.1 - JWT", description: "", acceptanceCriteria: "- [ ] ac" });

    const board = new BoardModel(root);
    board.rebuild();
    const cId = "folder:campaigns/q3";
    const mId = "folder:campaigns/q3/missions/m-skills";
    const tId = "folder:campaigns/q3/missions/m-skills/tasks/t-jwt";
    expect(board.listCampaigns().map((c) => c.id)).toEqual([cId]);
    expect(board.listMissions(cId).map((m) => m.id)).toEqual([mId]);
    expect(board.listTasks(mId).map((t) => t.id)).toEqual([tId]);
    expect(board.getTask(tId)?.name).toBe("T1.1 - JWT");
  });

  it("still reads a legacy marker when present (backward compat) — files without marker use folder-path id", () => {
    // A file with a legacy octobots:id marker is still indexed by that id.
    const cDir = join(root, "campaigns", "legacy");
    mkdirSync(cDir, { recursive: true });
    writeFileSync(
      join(cDir, "campaign.md"),
      "# Legacy\n<!-- octobots:id legacyid -->\n\n## Status\ndraft\n\n## Description\n_(not set)_\n\n## Acceptance Criteria\n_(not set)_\n\n<!-- Auto-generated by Octobots from the campaign's fields above. The orchestrator owns any sections appended below this comment. -->\n",
      "utf8",
    );
    const board = new BoardModel(root);
    board.rebuild();
    expect(board.getCampaign("legacyid")?.name).toBe("Legacy");
  });

  it("reports id-less files via missingIdFiles()", () => {
    const cDir = join(root, "campaigns", "legacy");
    writeBrief("campaign", cDir, { name: "Legacy", description: "", acceptanceCriteria: "", status: "draft", target: "" });
    const board = new BoardModel(root);
    board.rebuild();
    expect(board.missingIdFiles().some((f) => f.kind === "campaign")).toBe(true);
  });
});

describe("workflows", () => {
  it("parses a campaign workflow and a mission workflow", () => {
    const c = join(root, "campaigns", "alpha");
    mkdirSync(join(c, "workflows", "ship-missions"), { recursive: true });
    writeFileSync(join(c, "campaign.md"), "# Alpha\n\n## Description\nx\n");
    writeFileSync(
      join(c, "workflows", "ship-missions", "workflow.md"),
      "# ship-missions\n\n## Description\nShip them\n\n## Runs\n- [status:done] 2026-07-23 — ok\n",
    );
    writeFileSync(
      join(c, "workflows", "ship-missions", "workflow.js"),
      "export const meta = { name: 'ship-missions', description: 'd', phases: [{ title: 'Go', steps: [{ id: 's1', agent: 'a', label: 'l' }] }] }\n",
    );

    const m = join(c, "missions", "m1-auth");
    mkdirSync(join(m, "workflows", "build-tasks"), { recursive: true });
    writeFileSync(join(m, "mission.md"), "# M1 - Auth\n\n## Description\nx\n");
    writeFileSync(join(m, "workflows", "build-tasks", "workflow.md"), "# build-tasks\n\n## Description\nBuild\n");
    writeFileSync(
      join(m, "workflows", "build-tasks", "workflow.js"),
      "export const meta = { name: 'build-tasks', phases: [] }\n",
    );

    const board = new BoardModel(root);
    board.rebuild();

    const campaignId = board.listCampaigns()[0]!.id;
    const missionId = board.listMissions(campaignId)[0]!.id;

    const cw = board.listWorkflows({ campaignId });
    expect(cw).toHaveLength(1);
    expect(cw[0]!.name).toBe("ship-missions");
    expect(cw[0]!.campaignId).toBe(campaignId);
    expect(cw[0]!.missionId).toBeNull();
    expect(cw[0]!.phases[0]!.steps[0]!.agent).toBe("a");
    expect(cw[0]!.lastRunStatus).toBe("done");
    expect(cw[0]!.scriptPath).toBe("campaigns/alpha/workflows/ship-missions/workflow.js");
    expect(cw[0]!.parseError).toBeNull();

    const mw = board.listWorkflows({ missionId });
    expect(mw).toHaveLength(1);
    expect(mw[0]!.missionId).toBe(missionId);
    expect(mw[0]!.lastRunStatus).toBeNull();

    expect(board.getWorkflow(cw[0]!.id)!.name).toBe("ship-missions");
    expect(board.workflowIdByFolderPath("campaigns/alpha/workflows/ship-missions")).toBe(cw[0]!.id);
  });

  it("surfaces an unreadable script as parseError instead of dropping the workflow", () => {
    const c = join(root, "campaigns", "alpha");
    mkdirSync(join(c, "workflows", "broken"), { recursive: true });
    writeFileSync(join(c, "campaign.md"), "# Alpha\n\n## Description\nx\n");
    writeFileSync(join(c, "workflows", "broken", "workflow.md"), "# broken\n\n## Description\nd\n");
    writeFileSync(join(c, "workflows", "broken", "workflow.js"), "const notMeta = 1\n");

    const board = new BoardModel(root);
    board.rebuild();
    const campaignId = board.listCampaigns()[0]!.id;
    const [wf] = board.listWorkflows({ campaignId });
    expect(wf).toBeDefined();
    expect(wf!.parseError).toMatch(/export const meta/);
    expect(wf!.phases).toEqual([]);
    expect(wf!.name).toBe("broken");
  });
});
