import { describe, it, expect } from "vitest";
import { renderManagedBlock, parseManagedBlock } from "../src/managed-block.js";

describe("managed block round-trip", () => {
  it("renders a campaign and parses its fields back (no marker emitted — folder-path identity)", () => {
    const md = renderManagedBlock(
      "campaign",
      { id: "abc123", name: "Q3 Rollout", description: "Ship it", acceptanceCriteria: "- [ ] done", status: "draft", target: "main" },
      [],
      "orchestrator",
    );
    expect(md).toContain("# Q3 Rollout");
    // No marker is ever emitted — identity is folder-path based.
    expect(md).not.toContain("octobots:id");
    expect(md).toContain("<!-- Auto-generated by Octobots");
    const parsed = parseManagedBlock(md);
    // id is not written, so parsed.id is undefined for newly rendered blocks.
    expect(parsed.id).toBeUndefined();
    expect(parsed.name).toBe("Q3 Rollout");
    expect(parsed.description).toBe("Ship it");
    expect(parsed.target).toBe("main");
    expect(parsed.status).toBe("draft");
  });

  it("parseManagedBlock still reads a legacy marker for backward compatibility", () => {
    const legacy = "# Old Entity\n<!-- octobots:id legacyid123 -->\n\n## Description\nsome desc\n\n<!-- Auto-generated by Octobots ... -->\n";
    const parsed = parseManagedBlock(legacy);
    expect(parsed.id).toBe("legacyid123");
    expect(parsed.name).toBe("Old Entity");
  });

  it("treats a placeholder body as empty", () => {
    const md = renderManagedBlock("mission", { name: "M1 - x", description: "", acceptanceCriteria: "" }, [], "planner");
    expect(parseManagedBlock(md).description).toBe("");
  });
});
