/**
 * Tests for the automatic + safe md→yaml entity migration (`migrateEntitiesToYaml`).
 *
 * A legacy Markdown board is hand-written (the write layer only emits YAML now), then migrated:
 * every `<kind>.md` becomes a `<kind>.yaml` with NO lost status / role / severity / criteria /
 * documents / tokenomics — the parent's `[status:]`/`[role:]`/`[severity:]` board-line markers and a
 * `## Tokenomics` block fold into the CHILD's own file. The migration is idempotent and the `.md` is
 * trashed (not hard-deleted). Dual-read keeps a half-migrated board working.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { migrateEntitiesToYaml, createCampaign, createMission } from "../src/write.js";
import { BoardModel } from "../src/board-model.js";

let root: string; // the `.octobots` board root

beforeEach(() => {
  root = join(mkdtempSync(join(tmpdir(), "migrate-entities-")), ".octobots");
  mkdirSync(root, { recursive: true });
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

/** Write a file, creating parent dirs. */
function put(rel: string, body: string): void {
  const abs = join(root, rel);
  mkdirSync(join(abs, ".."), { recursive: true });
  writeFileSync(abs, body, "utf8");
}

const CAMPAIGN = "campaigns/q3";
const MISSION = `${CAMPAIGN}/missions/m1-auth`;
const TASK = `${MISSION}/tasks/t1-1-jwt`;
const BUG = `${MISSION}/bugs/b1-crash`;

/** Build a full legacy Markdown board: campaign → mission → task, plus a mission-level bug. */
function writeLegacyBoard(): void {
  put(
    `${CAMPAIGN}/campaign.md`,
    [
      "# Q3 Rollout",
      "",
      "## Status",
      "executing",
      "",
      "## Target",
      "Ship auth",
      "",
      "## Description",
      "Campaign desc",
      "",
      "## Acceptance Criteria",
      "- [ ] campaign done",
      "",
      "## Documents",
      "- [spec](docs/spec.md)",
      "",
      "<!-- Auto-generated by Octobots from the campaign's fields above. The planner owns any sections appended below this comment. -->",
      "",
      "## Missions",
      "- [status:active] M1 - Auth",
      "",
    ].join("\n"),
  );
  put(
    `${MISSION}/mission.md`,
    [
      "# M1 - Auth",
      "",
      "## Description",
      "Mission desc",
      "",
      "## Acceptance Criteria",
      "- [x] auth works",
      "",
      "## Documents",
      "- [plan](docs/plan.md)",
      "",
      "## Tokenomics",
      "effort_days: 3",
      "size_tshirt: M",
      "complexity_score: 18",
      "",
      "<!-- Auto-generated by Octobots from the mission's fields above. The planner owns any sections appended below this comment. -->",
      "",
      "## Tasks",
      "- [status:done] [role:python-dev] T1.1 - JWT",
      "",
      "## Bugs",
      "- [status:executing] B1 - Crash on login",
      "",
    ].join("\n"),
  );
  put(
    `${TASK}/task.md`,
    [
      "# T1.1 - JWT",
      "",
      "## Description",
      "Validate JWT",
      "",
      "## Acceptance Criteria",
      "- [ ] JWT validated on /login",
      "",
      "## Tokenomics",
      "effort_days: 1",
      "size_tshirt: S",
      "",
    ].join("\n"),
  );
  put(
    `${BUG}/bug.md`,
    [
      "# B1 - Crash on login",
      "",
      "## Severity",
      "critical",
      "",
      "## Description",
      "It crashes",
      "",
      "## Steps to Reproduce",
      "1. Log in",
      "",
      "## Expected",
      "No crash",
      "",
      "## Actual",
      "Crash",
      "",
    ].join("\n"),
  );
}

describe("migrateEntitiesToYaml — full legacy board", () => {
  it("migrates every entity to yaml with no lost fields, and trashes the .md", () => {
    writeLegacyBoard();

    const count = migrateEntitiesToYaml(root);
    expect(count).toBe(4); // campaign + mission + task + bug

    // Every `.md` is gone (trashed), every `.yaml` is present.
    for (const [folder, kind] of [
      [CAMPAIGN, "campaign"],
      [MISSION, "mission"],
      [TASK, "task"],
      [BUG, "bug"],
    ] as const) {
      expect(existsSync(join(root, folder, `${kind}.md`))).toBe(false);
      expect(existsSync(join(root, folder, `${kind}.yaml`))).toBe(true);
    }
    // Trash-not-delete: the .md content survives under .trash/.
    expect(existsSync(join(root, ".trash"))).toBe(true);

    const board = new BoardModel(root);
    board.rebuild();

    // Campaign: own ## Status, target, documents, acceptance criteria.
    const c = board.listCampaigns()[0]!;
    expect(c.status).toBe("executing");
    expect(c.target).toBe("Ship auth");
    expect(c.acceptanceCriteria).toContain("campaign done");
    // Documents are not on the read model — assert they landed in the campaign's own yaml.
    const campaignYaml = readFileSync(join(root, CAMPAIGN, "campaign.yaml"), "utf8");
    expect(campaignYaml).toContain("label: spec");
    expect(campaignYaml).toContain("target: docs/spec.md");

    // Mission: status folded from the campaign's `## Missions` marker (active→executing), documents,
    // and the `## Tokenomics` block folded into the tokenomics field.
    const m = board.listMissions(c.id)[0]!;
    expect(m.status).toBe("executing");
    expect(m.acceptanceCriteria).toContain("auth works");
    expect(m.tokenomics).toEqual({ effort_days: 3, size_tshirt: "M", complexity_score: 18 });
    const missionYaml = readFileSync(join(root, MISSION, "mission.yaml"), "utf8");
    expect(missionYaml).toContain("label: plan");
    expect(missionYaml).toContain("target: docs/plan.md");

    // Task: status + role folded from the mission's `## Tasks` marker; tokenomics folded.
    const t = board.listTasks(m.id)[0]!;
    expect(t.status).toBe("done");
    expect(t.acceptanceCriteria).toContain("JWT validated on /login");
    expect(t.tokenomics).toEqual({ effort_days: 1, size_tshirt: "S" });
    // Role is not on the read model — assert it landed in the child's own yaml.
    expect(readFileSync(join(root, TASK, "task.yaml"), "utf8")).toContain("role: python-dev");

    // Bug: status folded from the mission's `## Bugs` marker; severity from its own `## Severity`.
    const bug = board.listBugs({ missionId: m.id })[0]!;
    expect(bug.status).toBe("executing");
    expect(bug.severity).toBe("critical");
    expect(bug.description).toBe("It crashes");
  });

  it("is idempotent — a second run migrates nothing and does not rewrite the yaml", () => {
    writeLegacyBoard();
    expect(migrateEntitiesToYaml(root)).toBe(4);

    const snapshot = readFileSync(join(root, MISSION, "mission.yaml"), "utf8");
    expect(migrateEntitiesToYaml(root)).toBe(0);
    expect(readFileSync(join(root, MISSION, "mission.yaml"), "utf8")).toBe(snapshot);
  });

  it("never overwrites an existing <kind>.yaml (yaml wins, .md left untouched by that folder)", () => {
    writeLegacyBoard();
    // Pre-seed a task.yaml so the folder is considered already migrated.
    put(`${TASK}/task.yaml`, "name: T1.1 - JWT\nstatus: draft\ndescription: kept\nacceptance_criteria: []\n");

    const count = migrateEntitiesToYaml(root);
    // campaign + mission + bug migrate; the task folder is skipped (already yaml).
    expect(count).toBe(3);
    expect(readFileSync(join(root, TASK, "task.yaml"), "utf8")).toContain("description: kept");
    // The un-migrated task.md is left in place (that folder was skipped).
    expect(existsSync(join(root, TASK, "task.md"))).toBe(true);
  });
});

describe("migrateEntitiesToYaml — production data-loss regressions", () => {
  // LOSS 1: task `[status:]` markers were carried only when the `## Tasks` lines sat directly under
  // the heading. `add-task.js` appends below a `## Tokenomics` block, and the scan stopped at the
  // first `##` — orphaning every marker below it, regressing done→draft on a real 200-ticket board.
  it("carries `[status:]` markers on task lines that sit BELOW a `## Tokenomics` block", () => {
    put(`${CAMPAIGN}/campaign.md`, ["# Q3 Rollout", "", "## Status", "executing", ""].join("\n"));
    put(
      `${MISSION}/mission.md`,
      [
        "# M1 - Auth",
        "",
        "## Description",
        "Mission desc",
        "",
        "## Acceptance Criteria",
        "- [ ] auth works",
        "",
        "<!-- Auto-generated by Octobots from the mission's fields above. The planner owns any sections appended below this comment. -->",
        "",
        "## Tasks",
        "",
        "## Tokenomics",
        "effort_days: 3",
        "size_tshirt: M",
        "",
        // The append-below-tokenomics quirk: the task line lands here, after ## Tokenomics.
        "- [status:done] [role:python-dev] T1.1 - JWT",
        "",
      ].join("\n"),
    );
    put(
      `${TASK}/task.md`,
      ["# T1.1 - JWT", "", "## Description", "d", "", "## Acceptance Criteria", "- [ ] jwt", ""].join("\n"),
    );

    migrateEntitiesToYaml(root);
    const board = new BoardModel(root);
    board.rebuild();
    const c = board.listCampaigns()[0]!;
    const m = board.listMissions(c.id)[0]!;
    const t = board.listTasks(m.id)[0]!;
    expect(t.status).toBe("done"); // NOT regressed to draft
    // The role marker below ## Tokenomics is carried too.
    expect(readFileSync(join(root, TASK, "task.yaml"), "utf8")).toContain("role: python-dev");
  });

  // LOSS 2: free-form appended sections (`## Decision`, `## Update`, `## Product decisions`) held the
  // highest-value content — recorded decisions and product-owner sign-offs — and were silently
  // dropped because the migration mapped a fixed heading set with no destination for arbitrary prose.
  it("preserves unrecognised appended body sections into the entity's `notes` field", () => {
    put(`${CAMPAIGN}/campaign.md`, ["# Q3 Rollout", "", "## Status", "executing", ""].join("\n"));
    put(
      `${MISSION}/mission.md`,
      [
        "# M1 - Auth",
        "",
        "## Description",
        "Mission desc",
        "",
        "## Acceptance Criteria",
        "- [ ] auth works",
        "",
        "<!-- Auto-generated by Octobots from the mission's fields above. The planner owns any sections appended below this comment. -->",
        "",
        "## Tasks",
        "- [status:done] T1.1 - JWT",
        "",
        "## Decision",
        "Auth uses server clock, not client — multilateration needs a single time base.",
        "",
        "## Product decisions",
        "Signed off by the product owner on 2026-07-01.",
        "",
      ].join("\n"),
    );
    put(
      `${TASK}/task.md`,
      [
        "# T1.1 - JWT",
        "",
        "## Description",
        "d",
        "",
        "## Acceptance Criteria",
        "- [ ] jwt",
        "",
        "<!-- Auto-generated by Octobots from the task's fields above. The planner owns any sections appended below this comment. -->",
        "",
        "## Update",
        "Coach role folded into the admin role after review.",
        "",
      ].join("\n"),
    );

    migrateEntitiesToYaml(root);
    const board = new BoardModel(root);
    board.rebuild();
    const c = board.listCampaigns()[0]!;
    const m = board.listMissions(c.id)[0]!;
    const t = board.listTasks(m.id)[0]!;

    expect(m.notes).toContain("## Decision");
    expect(m.notes).toContain("single time base");
    expect(m.notes).toContain("## Product decisions");
    expect(m.notes).toContain("Signed off by the product owner");
    // The board-line projection under ## Tasks must NOT leak into notes.
    expect(m.notes).not.toContain("T1.1 - JWT");

    expect(t.notes).toContain("## Update");
    expect(t.notes).toContain("Coach role folded");

    // Round-trips through the yaml, so it survives every resync.
    expect(readFileSync(join(root, MISSION, "mission.yaml"), "utf8")).toContain("notes:");
  });

  // A mission with only structural + placeholder sections below the boundary has no notes.
  it("does not invent notes from placeholder-only or structural sections", () => {
    put(`${CAMPAIGN}/campaign.md`, ["# Q3 Rollout", "", "## Status", "executing", ""].join("\n"));
    put(
      `${MISSION}/mission.md`,
      [
        "# M1 - Auth",
        "",
        "## Description",
        "d",
        "",
        "## Acceptance Criteria",
        "- [ ] a",
        "",
        "<!-- Auto-generated by Octobots from the mission's fields above. The planner owns any sections appended below this comment. -->",
        "",
        "## Tasks",
        "_(no tasks yet)_",
        "",
        "## Tokenomics",
        "effort_days: 3",
        "",
      ].join("\n"),
    );

    migrateEntitiesToYaml(root);
    const board = new BoardModel(root);
    board.rebuild();
    const m = board.listMissions(board.listCampaigns()[0]!.id)[0]!;
    expect(m.notes).toBeUndefined();
  });
});

describe("migrateEntitiesToYaml — dual-read overlap", () => {
  it("a half-migrated board (yaml parent, legacy md child) still reads via dual-read", () => {
    // Campaign + mission written as YAML by the current write layer…
    const c = createCampaign(root, { name: "Q3 Rollout" });
    const m = createMission(root, c.id, { title: "M1 - Auth", acceptanceCriteria: "- [ ] auth works" });
    // …but a task still on legacy markdown (no task.yaml yet).
    put(
      `${m.folderPath}/tasks/t1-1-jwt/task.md`,
      ["# T1.1 - JWT", "", "## Description", "d", "", "## Acceptance Criteria", "- [ ] jwt", ""].join("\n"),
    );

    const board = new BoardModel(root);
    board.rebuild();
    const tasks = board.listTasks(m.id);
    expect(tasks.some((t) => t.name === "T1.1 - JWT")).toBe(true);
  });
});
