import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createCampaign, createMission, createTask, setStatus } from "../src/write.js";
import { BoardModel } from "../src/board-model.js";

let root: string;
beforeEach(() => { root = mkdtempSync(join(tmpdir(), "board-ms-")); });
afterEach(() => { rmSync(root, { recursive: true, force: true }); });

describe("mission status", () => {
  it("reads status from a legacy .md parent board line (migration fallback)", () => {
    // A not-yet-migrated markdown board: status on the campaign.md `## Missions` line.
    const cDir = join(root, "campaigns", "q3");
    const mDir = join(cDir, "missions", "m1-skills");
    mkdirSync(mDir, { recursive: true });
    writeFileSync(
      join(cDir, "campaign.md"),
      "# Q3\n\n## Description\nx\n\n<!-- Auto-generated by Octobots -->\n## Missions\n- [status:executing] M1 - Skills\n",
    );
    writeFileSync(
      join(mDir, "mission.md"),
      "# M1 - Skills\n\n## Description\nd\n\n## Acceptance Criteria\n- [ ] ac\n\n<!-- Auto-generated by Octobots -->\n## Tasks\n_(none)_\n",
    );
    const board = new BoardModel(root);
    board.rebuild();
    const campaignId = board.listCampaigns()[0]!.id;
    expect(board.listMissions(campaignId)[0]?.status).toBe("executing");
  });

  it("defaults to 'draft' when a fresh mission has no status set", () => {
    const c = createCampaign(root, { name: "Q3" });
    const m = createMission(root, c.id, { title: "M2 - Auth", acceptanceCriteria: "- [ ] ac" });
    const board = new BoardModel(root);
    board.rebuild();
    expect(board.getMission(m.id)?.status).toBe("draft");
  });

  it("round-trips status for an em-dash `<id> — name` mission title", () => {
    const c = createCampaign(root, { name: "Octoweb" });
    const m = createMission(root, c.id, { title: "M9 — Agent filesystem substrate", acceptanceCriteria: "- [ ] ac" });
    expect(setStatus(root, "mission", m.id, "executing")).toBe(true);
    const board = new BoardModel(root);
    board.rebuild();
    expect(board.getMission(m.id)?.status).toBe("executing");
  });

  it("round-trips status for an em-dash task title", () => {
    const c = createCampaign(root, { name: "Octoweb" });
    const m = createMission(root, c.id, { title: "M9 — Substrate", acceptanceCriteria: "- [ ] ac" });
    createTask(root, m.id, { name: "T9.1 — Wire the loader", acceptanceCriteria: "- [ ] ac" });
    const t0 = new BoardModel(root); t0.rebuild();
    const taskId = t0.listTasks(m.id)[0]!.id;
    expect(setStatus(root, "task", taskId, "done")).toBe(true);
    const board = new BoardModel(root);
    board.rebuild();
    expect(board.getTask(taskId)?.status).toBe("done");
  });
});
