import { describe, it, expect } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { BoardModel, setStatus, setTeam, getTeam, updateBrief } from "../src/index.js";

function fixture(): { root: string; campId: string; missId: string } {
  const root = mkdtempSync(join(tmpdir(), "board-team-"));
  const cDir = join(root, "campaigns/c");
  const mDir = join(cDir, "missions/m");
  mkdirSync(mDir, { recursive: true });
  writeFileSync(join(cDir, "campaign.md"),
    "# C\n\n## Description\nd\n\n<!-- Auto-generated by Octobots -->\n## Missions\n- M1 - Build it\n", "utf8");
  writeFileSync(join(mDir, "mission.md"),
    "# M1 - Build it\n\n## Description\nd\n\n<!-- Auto-generated by Octobots -->\n## Tasks\n_(none yet)_\n", "utf8");
  const model = new BoardModel(root);
  model.rebuild();
  const campId = model.listCampaigns()[0]!.id;
  const missId = model.listMissions(campId)[0]!.id;
  return { root, campId, missId };
}

describe("mission status marker", () => {
  it("setStatus writes a [status:X] marker on the mission's ## Missions line", () => {
    const { root, missId } = fixture();
    expect(setStatus(root, "mission", missId, "active")).toBe(true);
    const bm = new BoardModel(root);
    bm.rebuild();
    expect(bm.getMission(missId)!.status).toBe("executing");
  });
});

describe("team markers", () => {
  it("setTeam adds a [team:slug] marker; getTeam reads it; null clears it", () => {
    const { root, campId, missId } = fixture();
    expect(setTeam(root, "mission", missId, "alpha-squad")).toBe(true);
    expect(getTeam(root, "mission", missId)).toBe("alpha-squad");
    expect(setTeam(root, "campaign", campId, "beta")).toBe(true);
    expect(getTeam(root, "campaign", campId)).toBe("beta");
    expect(setTeam(root, "mission", missId, null)).toBe(true);
    expect(getTeam(root, "mission", missId)).toBeNull();
  });

  it("campaign team binding survives updateBrief (lives in the preserved tail)", () => {
    const { root, campId } = fixture();
    expect(setTeam(root, "campaign", campId, "alpha")).toBe(true);
    expect(getTeam(root, "campaign", campId)).toBe("alpha");
    updateBrief(root, "campaign", campId, { description: "new desc" });
    expect(getTeam(root, "campaign", campId)).toBe("alpha"); // must NOT be lost
  });
});
