/**
 * The app's read-modify-write path (`patchEntity` → `loadCurrentFields`) tolerates an entity still
 * on a legacy `<kind>.md`: it parses the markdown, writes `<kind>.yaml`, and trashes the `.md`.
 * That conversion must carry the free-form prose below the managed block — the recorded decisions
 * and sign-offs — or the first status change on a not-yet-migrated board destroys them.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { setStatus, setCriterion } from "../src/write.js";
import { loadEntity } from "../src/entity-schema.js";
import { BoardModel } from "../src/board-model.js";

let boardRoot: string;

beforeEach(() => {
  boardRoot = join(mkdtempSync(join(tmpdir(), "write-md-notes-")), ".octobots");
  mkdirSync(boardRoot, { recursive: true });
});
afterEach(() => {
  rmSync(join(boardRoot, ".."), { recursive: true, force: true });
});

const DECISION = "## Decision 2026-07-20\nRS256 only; HS256 is rejected outright.";

/** A legacy markdown board with one campaign → mission → task, the task carrying appended prose. */
function legacyBoard(): { taskDir: string } {
  const cDir = join(boardRoot, "campaigns", "q3");
  const mDir = join(cDir, "missions", "m1-auth");
  const tDir = join(mDir, "tasks", "t1-1-jwt");
  mkdirSync(tDir, { recursive: true });
  writeFileSync(
    join(cDir, "campaign.md"),
    ["# Q3 Rollout", "", "## Description", "c", "", "## Acceptance Criteria", "- [ ] shipped", ""].join("\n"),
    "utf8",
  );
  writeFileSync(
    join(mDir, "mission.md"),
    ["# M1 - Auth", "", "## Description", "m", "", "## Acceptance Criteria", "- [ ] works", ""].join("\n"),
    "utf8",
  );
  writeFileSync(
    join(tDir, "task.md"),
    [
      "# T1.1 - JWT",
      "",
      "## Description",
      "validate tokens",
      "",
      "## Acceptance Criteria",
      "- [ ] jwt validated",
      "",
      "<!-- Auto-generated by Octobots from the task's fields above. -->",
      "",
      DECISION,
      "",
    ].join("\n"),
    "utf8",
  );
  return { taskDir: tDir };
}

function taskId(): string {
  const board = new BoardModel(boardRoot);
  board.rebuild();
  const c = board.listCampaigns()[0]!;
  const m = board.listMissions(c.id)[0]!;
  return board.listTasks(m.id)[0]!.id;
}

describe("converting a legacy .md entity on write", () => {
  it("keeps the appended decision when setStatus migrates the task to yaml", () => {
    const { taskDir } = legacyBoard();

    expect(setStatus(boardRoot, "task", taskId(), "done")).toBe(true);

    const yamlPath = join(taskDir, "task.yaml");
    expect(existsSync(yamlPath)).toBe(true);
    const after = loadEntity(readFileSync(yamlPath, "utf8"));
    expect(after.notes).toContain("RS256 only; HS256 is rejected outright.");
    expect(after.status).toBe("done");
    expect(after.description).toBe("validate tokens");
    expect(after.acceptanceCriteria).toEqual([{ text: "jwt validated", done: false }]);
  });

  it("keeps the appended decision when setCriterion migrates the task to yaml", () => {
    const { taskDir } = legacyBoard();

    expect(setCriterion(boardRoot, "task", taskId(), 1, true)).toBe(true);

    const after = loadEntity(readFileSync(join(taskDir, "task.yaml"), "utf8"));
    expect(after.notes).toContain("RS256 only; HS256 is rejected outright.");
    expect(after.acceptanceCriteria).toEqual([{ text: "jwt validated", done: true }]);
  });

  it("matches what the standalone migration would have produced for notes", () => {
    const { taskDir } = legacyBoard();
    setStatus(boardRoot, "task", taskId(), "done");

    const viaWrite = loadEntity(readFileSync(join(taskDir, "task.yaml"), "utf8")).notes;
    expect(viaWrite).toBe(DECISION);
  });
});
