#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, statSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { randomUUID } from "node:crypto";

// Create a mission under a campaign: `<campaignDir>/missions/<slug>/mission.md`, and project it onto
// the campaign's `## Missions` board. Disk is the source of truth — a mission IS its folder,
// identified by its folder path (`folder:<relPath>`); no marker is written. A bare `## Missions`
// board line is only a status projection, never a create trigger, so always create via this script.
// The mission starts with a placeholder `## Acceptance Criteria` — add real criteria with
// set-criterion.js (validate.js requires at least one), exactly as add-task.js does for a task.
const rawArgs = process.argv.slice(2);
let description = "";
const positional = [];
for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === "--description") description = (rawArgs[++i] ?? "").trim();
  else positional.push(rawArgs[i]);
}

const arg = positional[0];
const title = (positional[1] ?? "").trim();
if (!arg || !title) {
  console.error('usage: add-mission.js <campaign.md|campaign-dir> "<title>" [--description <text>]');
  process.exit(2);
}
const campaignMd = existsSync(arg) && statSync(arg).isDirectory() ? join(arg, "campaign.md") : arg;
if (!existsSync(campaignMd)) { console.error(`add-mission: file not found: ${campaignMd}`); process.exit(2); }
const campaignDir = dirname(campaignMd);

const newId = () => randomUUID().replace(/-/g, "").slice(0, 12);
const slugify = (s) => {
  const out = s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 50).replace(/-+$/g, "");
  return out || newId().slice(0, 8);
};
const missionsDir = join(campaignDir, "missions");
const taken = existsSync(missionsDir)
  ? new Set(readdirSync(missionsDir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name))
  : new Set();
let slug = slugify(title);
if (taken.has(slug)) { for (let n = 2; ; n++) { if (!taken.has(`${slug}-${n}`)) { slug = `${slug}-${n}`; break; } } }
const missionDir = join(missionsDir, slug);
mkdirSync(missionDir, { recursive: true });

// `## Documents` is the app-managed link section (round-trips add-doc.js links); `## Tasks` below the
// boundary is the planner-owned section add-task.js appends to.
const missionMd =
  `# ${title}\n\n` +
  `## Description\n${description || "_(not set)_"}\n\n` +
  `## Acceptance Criteria\n_(not set)_\n\n` +
  `## Documents\n_(none)_\n\n` +
  `<!-- Auto-generated by Octobots from the mission's fields above. The planner owns any sections appended below this comment. -->\n` +
  `## Tasks\n_(none yet — the planner proposes tasks here)_\n`;
writeFileSync(join(missionDir, "mission.md"), missionMd, "utf8");

// Project the mission onto the campaign's `## Missions` board, dropping any lone italic placeholder
// (e.g. "_(none yet — …)_") so it doesn't linger above the first real mission.
const line = `- ${title}`;
let text = readFileSync(campaignMd, "utf8");
if (!text.endsWith("\n")) text += "\n";
if (/^##\s+Missions\s*$/m.test(text)) {
  const at = text.search(/^##\s+Missions\s*$/m);
  const headEnd = text.indexOf("\n", at) + 1;
  const head = text.slice(0, headEnd);
  const body = text.slice(headEnd).replace(/^[ \t]*_\(.*?\)_[ \t]*\n/gm, "");
  text = head + body;
  if (!text.endsWith("\n")) text += "\n";
  text += line + "\n";
} else {
  text += `## Missions\n${line}\n`;
}
writeFileSync(campaignMd, text, "utf8");
console.log(`added mission: ${title} (missions/${slug})`);
