#!/usr/bin/env node
// Append a run entry to a workflow's `## Runs` log.
//
//   add-run.js --workflow <workflow-dir> --status <done|failed|cancelled|executing>
//              --summary "<text>" [--at YYYY-MM-DD]
//
// The board reads the newest `- [status:x] …` line as the workflow's last run status.

import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const tok = argv[i];
    if (tok.startsWith("--")) {
      args[tok.slice(2)] = argv[i + 1] ?? "";
      i++;
    }
  }
  return args;
}

const { workflow, status, summary, at } = parseArgs(process.argv.slice(2));

if (!workflow || !status || !summary) {
  console.error(
    'usage: add-run.js --workflow <workflow-dir> --status <done|failed|cancelled|executing> ' +
      '--summary "<text>" [--at YYYY-MM-DD]',
  );
  process.exit(2);
}

const dir = existsSync(workflow) && statSync(workflow).isDirectory() ? workflow : null;
if (!dir) { console.error(`add-run: not a directory: ${workflow}`); process.exit(2); }

const mdPath = join(dir, "workflow.md");
if (!existsSync(mdPath)) { console.error(`add-run: workflow.md not found in ${workflow}`); process.exit(2); }

const when = (at ?? "").trim() || new Date().toISOString().slice(0, 10);
const line = `- [status:${status}] ${when} — ${summary}`;

let text = readFileSync(mdPath, "utf8");
const head = text.search(/^##\s+Runs\s*$/m);

if (head < 0) {
  // No Runs section (hand-written file) — create it above the boundary comment so the app parses it.
  const boundary = text.indexOf("<!-- Auto-generated by Octobots");
  const insertAt = boundary >= 0 ? boundary : text.length;
  text = `${text.slice(0, insertAt)}## Runs\n${line}\n\n${text.slice(insertAt)}`;
} else {
  const rest = text.slice(head);
  const nextHeading = rest.search(/\n(?=##\s+|<!--)/);
  const insertAt = nextHeading >= 0 ? head + nextHeading : text.length;
  const before = text.slice(0, insertAt).replace(/\n?_\(not set\)_\n?/, "\n");
  text = `${before.endsWith("\n") ? before : before + "\n"}${line}\n${text.slice(insertAt)}`;
}

writeFileSync(mdPath, text, "utf8");
console.log(line);
