#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, statSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { randomUUID } from "node:crypto";

// Parse argv: extract optional --severity <level> flag (anywhere), leaving positional args.
const rawArgs = process.argv.slice(2);
let severity = null;
const positional = [];
for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === "--severity") {
    severity = (rawArgs[++i] ?? "").trim().toLowerCase() || null;
  } else {
    positional.push(rawArgs[i]);
  }
}

const arg = positional[0];
const title = (positional[1] ?? "").trim();
if (!arg || !title) {
  console.error('usage: add-bug.js <campaign.md|mission.md|entity-dir> "<title>" [--severity blocker|critical|major|minor|trivial]');
  process.exit(2);
}
const SEVERITIES = ["blocker", "critical", "major", "minor", "trivial"];
if (severity && !SEVERITIES.includes(severity)) {
  console.error(`add-bug: invalid severity "${severity}" (expected one of: ${SEVERITIES.join(", ")})`);
  process.exit(2);
}
// Resolve a directory arg to its brief: prefer mission.md, else campaign.md.
let path = arg;
if (existsSync(arg) && statSync(arg).isDirectory()) {
  const mission = join(arg, "mission.md");
  path = existsSync(mission) ? mission : join(arg, "campaign.md");
}
if (!existsSync(path)) { console.error(`add-bug: file not found: ${path}`); process.exit(2); }
const parentDir = dirname(path);
const sev = severity || "major";

// Disk is the source of truth: a bug IS a `bugs/<slug>/bug.md` folder. Entities are identified
// by their folder path (`folder:<relPath>`); no marker is written. Create the folder here — a bare
// `## Bugs` board line is only a status/severity projection, never a create trigger.
const newId = () => randomUUID().replace(/-/g, "").slice(0, 12);
const slugify = (name) => {
  const s = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 50).replace(/-+$/g, "");
  return s || newId().slice(0, 8);
};
const bugsDir = join(parentDir, "bugs");
const taken = existsSync(bugsDir)
  ? new Set(readdirSync(bugsDir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name))
  : new Set();
let slug = slugify(title);
if (taken.has(slug)) { for (let n = 2; ; n++) { if (!taken.has(`${slug}-${n}`)) { slug = `${slug}-${n}`; break; } } }
const bugDir = join(bugsDir, slug);
mkdirSync(bugDir, { recursive: true });
const bugMd =
  `# ${title}\n\n` +
  `## Severity\n${sev}\n\n` +
  `## Description\n_(not set)_\n\n` +
  `## Steps to Reproduce\n_(not set)_\n\n` +
  `## Expected\n_(not set)_\n\n` +
  `## Actual\n_(not set)_\n\n` +
  `## RCA\n_(not set)_\n\n` +
  `## Environment\n_(not set)_\n\n` +
  `<!-- Auto-generated by Octobots from the bug's fields above. The planner owns any sections appended below this comment. -->\n`;
writeFileSync(join(bugDir, "bug.md"), bugMd, "utf8");

// Project the bug onto the parent's `## Bugs` board (display + severity/status markers).
const placeholder = "_(no bugs yet)_";
const marker = severity && severity !== "major" ? `[severity:${severity}] ` : "";
const line = `- ${marker}${title}`;
let text = readFileSync(path, "utf8");
if (text.includes(placeholder)) {
  text = text.replace(placeholder, line);
} else if (/^##\s+Bugs\s*$/m.test(text)) {
  text = (text.endsWith("\n") ? text : text + "\n") + line + "\n";
} else {
  text = (text.endsWith("\n") ? text : text + "\n") + `## Bugs\n${line}\n`;
}
writeFileSync(path, text, "utf8");
console.log(`added bug: ${title} (bugs/${slug})`);
