#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, statSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { randomUUID } from "node:crypto";

// Parse argv: extract optional --role <name> flag (anywhere), leaving positional args.
const rawArgs = process.argv.slice(2);
let role = null;
const positional = [];
for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === "--role") {
    role = (rawArgs[++i] ?? "").trim() || null;
  } else {
    positional.push(rawArgs[i]);
  }
}

const arg = positional[0];
const title = (positional[1] ?? "").trim();
if (!arg || !title) {
  console.error('usage: add-task.js <mission.md|mission-dir> "<title>" [--role <name>]');
  process.exit(2);
}
const missionMd = existsSync(arg) && statSync(arg).isDirectory() ? join(arg, "mission.md") : arg;
if (!existsSync(missionMd)) { console.error(`add-task: file not found: ${missionMd}`); process.exit(2); }
const missionDir = dirname(missionMd);

// Disk is the source of truth: a task IS a `tasks/<slug>/task.md` folder. Entities are identified
// by their folder path (`folder:<relPath>`); no marker is written. Create the folder here — a bare
// `## Tasks` board line is only a status/role projection, never a create trigger.
const newId = () => randomUUID().replace(/-/g, "").slice(0, 12);
const slugify = (name) => {
  const s = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 50).replace(/-+$/g, "");
  return s || newId().slice(0, 8);
};
const tasksDir = join(missionDir, "tasks");
const taken = existsSync(tasksDir)
  ? new Set(readdirSync(tasksDir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name))
  : new Set();
let slug = slugify(title);
if (taken.has(slug)) { for (let n = 2; ; n++) { if (!taken.has(`${slug}-${n}`)) { slug = `${slug}-${n}`; break; } } }
const taskDir = join(tasksDir, slug);
mkdirSync(taskDir, { recursive: true });
const taskMd =
  `# ${title}\n\n` +
  `## Description\n_(not set)_\n\n` +
  `## Acceptance Criteria\n_(not set)_\n\n` +
  `<!-- Auto-generated by Octobots from the task's fields above. The planner owns any sections appended below this comment. -->\n`;
writeFileSync(join(taskDir, "task.md"), taskMd, "utf8");

// Project the task onto the parent mission's `## Tasks` board (display + role/status markers).
const placeholder = "_(none yet — the planner proposes tasks here)_";
const taskContent = role ? `[role:${role}] ${title}` : title;
const line = `- ${taskContent}`;
let text = readFileSync(missionMd, "utf8");
if (text.includes(placeholder)) {
  text = text.replace(placeholder, line);
} else if (/^##\s+Tasks\s*$/m.test(text)) {
  text = (text.endsWith("\n") ? text : text + "\n") + line + "\n"; // ## Tasks is the last section
} else {
  text = (text.endsWith("\n") ? text : text + "\n") + `## Tasks\n${line}\n`;
}
writeFileSync(missionMd, text, "utf8");
console.log(`added task: ${title} (tasks/${slug})`);
