#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { dumpEntity, loadEntity, mapBoardStatus, childDirs } from "./entity-io.mjs";

// One-time, idempotent md→yaml entity migration for CLI-first boards (the app runs the same sweep on
// activation). For every entity folder that still has a legacy `<kind>.md` and no `<kind>.yaml`, parse
// the `.md`, fold the parent's `[status:]`/`[role:]`/`[severity:]` board-line markers and a
// `## Tokenomics` block into the CHILD's own yaml, write `<kind>.yaml`, then TRASH (not delete) the
// `.md`. A folder already on yaml is skipped; an existing yaml is never overwritten. Dual-read keeps a
// half-migrated board working mid-sweep. Mirrors packages/board/src/write.ts `migrateEntitiesToYaml`.
//
// Usage: migrate.js [--root <dir>]   (root defaults to `.octobots`)
const rawArgs = process.argv.slice(2);
let root = ".octobots";
for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === "--root") root = (rawArgs[++i] ?? "").trim() || ".octobots";
}
if (!existsSync(root)) {
  console.error(`migrate: board root not found: ${root}`);
  process.exit(2);
}

// ── md parsing helpers (mirror managed-block.ts / write.ts) ─────────────────────
function mdSection(text, label) {
  const m = new RegExp(`^##\\s+${label}\\s*$`, "m").exec(text);
  if (!m) return "";
  const rest = text.slice(m.index + m[0].length);
  const ends = [rest.search(/^##\s+/m), rest.search(/^<!--/m)].filter((n) => n >= 0);
  const body = (ends.length ? rest.slice(0, Math.min(...ends)) : rest).trim();
  return /^_\(.*\)_$/.test(body) ? "" : body;
}
function heading(text) {
  const h = /^#\s+(.+?)\s*$/m.exec(text);
  return h ? h[1].trim() : "";
}
function parseCriteria(body) {
  const out = [];
  for (const line of body.split("\n")) {
    const m = line.match(/^\s*-\s*\[([ xX])\]\s*(.*)$/);
    if (m) out.push({ text: (m[2] ?? "").trim(), done: (m[1] ?? " ").toLowerCase() === "x" });
  }
  return out;
}
function parseDocuments(body) {
  const out = [];
  const seen = new Set();
  for (const line of body.split("\n")) {
    const m = line.match(/^\s*-\s+\[(.+?)\]\((.+?)\)\s*$/);
    if (!m) continue;
    const target = (m[2] ?? "").trim();
    if (!target || seen.has(target)) continue;
    seen.add(target);
    out.push({ label: (m[1] ?? "").trim() || target, target });
  }
  return out;
}
function boardLineEntityName(bareTitle) {
  const cleaned = bareTitle.replace(/^\[[ xX]\]\s*/, "").replace(/\*\*/g, "").trim();
  const sep = cleaned.match(/\s+[—–]\s+|:\s+/);
  return sep ? cleaned.slice(0, sep.index).trim() : cleaned;
}

/** Map from a child board-line name (lowercased) → { status, role, severity } markers on that line. */
function parseParentMarkers(text, section) {
  const out = new Map();
  if (!text) return out;
  const boundaryIdx = text.indexOf("<!-- Auto-generated by Octobots");
  const scan = boundaryIdx >= 0 ? text.slice(boundaryIdx) : text;
  const head = new RegExp(`^${section}\\s*$`, "m").exec(scan);
  if (!head) return out;
  const after = scan.slice(head.index + head[0].length);
  const nextHeading = after.search(/^##\s+/m);
  const body = nextHeading >= 0 ? after.slice(0, nextHeading) : after;
  for (const line of body.split("\n")) {
    const bullet = line.match(/^[-*]\s+(.*)$/) ?? line.match(/^\d+[.)]\s+(.*)/);
    if (!bullet) continue;
    let rest = bullet[1] ?? "";
    const marker = {};
    for (;;) {
      const m = rest.match(/^\[([a-z]+):([^\]]*)\]\s*/i);
      if (!m) break;
      const key = (m[1] ?? "").toLowerCase();
      const val = (m[2] ?? "").trim();
      if (key === "status") marker.status = mapBoardStatus(val) ?? undefined;
      else if (key === "role") marker.role = val || undefined;
      else if (key === "severity") marker.severity = val || undefined;
      rest = rest.slice(m[0].length);
    }
    const nameKey = boardLineEntityName(rest).toLowerCase();
    if (nameKey) out.set(nameKey, marker);
  }
  return out;
}

/** Fold a legacy `## Tokenomics` block (`key: value` lines) into the open tokenomics map, or undefined. */
function parseTokenomicsBlock(md) {
  const block = /^##[ \t]+Tokenomics[ \t]*\n([\s\S]*?)(?=\n##\s|\n<!--|$(?![\s\S]))/m.exec(md)?.[1];
  if (block === undefined) return undefined;
  const out = {};
  for (const line of block.split("\n")) {
    const m = /^\s*[-*]?\s*([a-z_]+)\s*:\s*(.+?)\s*$/i.exec(line);
    if (!m || !m[1] || m[2] === undefined) continue;
    const raw = m[2].trim();
    let val = raw;
    if (/^-?\d+(\.\d+)?$/.test(raw)) val = Number(raw);
    else if (raw === "true" || raw === "false") val = raw === "true";
    out[m[1].toLowerCase()] = val;
  }
  return Object.keys(out).length ? out : undefined;
}

/**
 * Capture free-form appended prose the migration would otherwise silently drop. Below the
 * managed-block boundary an agent may record decisions, rationale, or product sign-offs under their
 * own `##` headings (`## Decision`, `## Update`, …). Everything below the boundary that is NOT a
 * recognised structural section — the board-line projections, the folded `## Tokenomics`, or a
 * placeholder-only stub — is preserved verbatim into `notes`. Mirrors write.ts `parseNotes`.
 */
function parseNotes(md) {
  const marker = md.indexOf("Auto-generated by Octobots");
  if (marker < 0) return undefined;
  const close = md.indexOf("-->", marker);
  if (close < 0) return undefined;
  const tail = md.slice(close + 3);
  const STRUCTURAL = /^(Tasks|Bugs|Missions|Tokenomics|Sessions|Runs)\b/i;
  const kept = [];
  for (const part of tail.split(/(?=^##[ \t]+)/m)) {
    const h = /^##[ \t]+(.+?)[ \t]*$/m.exec(part);
    if (h && STRUCTURAL.test(h[1] ?? "")) continue;
    const stripped = part.replace(/^##[ \t]+.*$/m, "").replace(/_\([^)]*\)_/g, "").trim();
    if (!stripped) continue;
    kept.push(part.trim());
  }
  return kept.join("\n\n").trim() || undefined;
}

/** Trash a single file under `<root>/.trash/<name>` (suffixing on collision); rmSync on error. */
function trashFile(file) {
  if (!existsSync(file)) return;
  try {
    const trash = join(root, ".trash");
    mkdirSync(trash, { recursive: true });
    let dest = join(trash, basename(file));
    for (let n = 2; existsSync(dest); n++) dest = join(trash, `${basename(file)}-${n}`);
    renameSync(file, dest);
    return;
  } catch {
    /* fall through */
  }
  try {
    rmSync(file, { force: true });
  } catch {
    /* ignore */
  }
}

/** Migrate one entity folder's `<kind>.md` → `<kind>.yaml`. Returns true iff a `.md` was migrated. */
function migrateOne(folder, kind, markers) {
  const mdPath = join(folder, `${kind}.md`);
  const yamlPath = join(folder, `${kind}.yaml`);
  if (!existsSync(mdPath) || existsSync(yamlPath)) return false; // only migrate md-without-yaml

  const md = readFileSync(mdPath, "utf8");
  const name = heading(md);
  const marker = markers ? markers.get(boardLineEntityName(name).toLowerCase()) : undefined;
  const ownStatusRaw = mdSection(md, "Status");
  const ownStatus = ownStatusRaw ? mapBoardStatus(ownStatusRaw) ?? ownStatusRaw : undefined;

  const fields = {
    name,
    description: mdSection(md, "Description"),
    acceptanceCriteria: parseCriteria(mdSection(md, "Acceptance Criteria")),
    documents: parseDocuments(mdSection(md, "Documents")),
    status: kind === "campaign" ? ownStatus : marker?.status,
    role: marker?.role,
    target: mdSection(md, "Target") || undefined,
    severity: kind === "bug" ? mdSection(md, "Severity").toLowerCase() || marker?.severity : undefined,
    stepsToReproduce: mdSection(md, "Steps to Reproduce") || undefined,
    expected: mdSection(md, "Expected") || undefined,
    actual: mdSection(md, "Actual") || undefined,
    rca: mdSection(md, "RCA") || undefined,
    environment: mdSection(md, "Environment") || undefined,
    tokenomics: kind === "mission" || kind === "task" ? parseTokenomicsBlock(md) : undefined,
    // Preserve any free-form appended prose (recorded decisions/rationale/sign-offs) verbatim.
    notes: parseNotes(md),
  };

  writeFileSync(yamlPath, dumpEntity(kind, fields), "utf8");
  // Reversible-ish: re-read the yaml before trashing the source — bail on a bad read.
  try {
    loadEntity(readFileSync(yamlPath, "utf8"));
  } catch {
    return false;
  }
  trashFile(mdPath);
  return true;
}

const readIf = (p) => (existsSync(p) ? readFileSync(p, "utf8") : "");

let migrated = 0;
const campaignsDir = join(root, "campaigns");
for (const cslug of childDirs(campaignsDir)) {
  const cFolder = join(campaignsDir, cslug);
  const cMd = readIf(join(cFolder, "campaign.md"));
  const cBugMarkers = parseParentMarkers(cMd, "## Bugs");
  const cMissionMarkers = parseParentMarkers(cMd, "## Missions");

  for (const bslug of childDirs(join(cFolder, "bugs"))) {
    if (migrateOne(join(cFolder, "bugs", bslug), "bug", cBugMarkers)) migrated++;
  }

  for (const mslug of childDirs(join(cFolder, "missions"))) {
    const mFolder = join(cFolder, "missions", mslug);
    const mMd = readIf(join(mFolder, "mission.md"));
    const mBugMarkers = parseParentMarkers(mMd, "## Bugs");
    const mTaskMarkers = parseParentMarkers(mMd, "## Tasks");
    for (const bslug of childDirs(join(mFolder, "bugs"))) {
      if (migrateOne(join(mFolder, "bugs", bslug), "bug", mBugMarkers)) migrated++;
    }
    for (const tslug of childDirs(join(mFolder, "tasks"))) {
      if (migrateOne(join(mFolder, "tasks", tslug), "task", mTaskMarkers)) migrated++;
    }
    if (migrateOne(mFolder, "mission", cMissionMarkers)) migrated++;
  }

  if (migrateOne(cFolder, "campaign", null)) migrated++;
}

console.log(`migrated ${migrated} entity file(s) to yaml`);
