#!/usr/bin/env node
import { readFileSync, existsSync } from "node:fs";
import { basename } from "node:path";

const path = process.argv[2];
if (!path || !existsSync(path)) {
  console.error(`validate: file not found: ${path ?? "(none)"}`);
  process.exit(2);
}
const text = readFileSync(path, "utf8");
const kind = basename(path).replace(/\.md$/, ""); // campaign | mission | task | bug
const problems = [];

// Title present + descriptive (not a placeholder like "T1" / "M3.2" / "Task 3").
const titleM = /^#\s+(.+?)\s*$/m.exec(text);
if (!titleM) {
  problems.push("missing a `# Title` heading");
} else if (isPlaceholderName(titleM[1])) {
  problems.push(
    `title "${titleM[1].trim()}" is just an id/placeholder — use the form \`<id> - descriptive name\` ` +
      `(e.g. "M3 - Skills workspace", "T3.1 - Add JWT validation to /login"); the bare id alone is not a name`,
  );
}

if (!text.includes("Auto-generated by Octobots") && !text.includes("Auto-generated by Octoshell")) {
  problems.push("missing the `Auto-generated by Octobots` boundary comment");
}
if (!/^##\s+(Tasks|Missions|Bugs)\s*$/m.test(text)) {
  problems.push("missing an agent-owned `## Tasks`, `## Missions`, or `## Bugs` section");
}

// Missions and tasks must carry at least one verifiable acceptance criterion.
if ((kind === "mission" || kind === "task") && !hasAcceptanceCriterion()) {
  problems.push(
    "no acceptance criteria — add at least one checkable `- [ ]` item under `## Acceptance Criteria` " +
      "(use set-criterion.js); a task/mission without a verifiable criterion is not well-formed",
  );
}

// A mission's `## Tasks` items must be descriptively named, not "T1"/"T5.5".
if (kind === "mission") {
  for (const name of taskNames()) {
    if (isPlaceholderName(name)) {
      problems.push(
        `task "${name.trim()}" is just an id — use \`<id> - descriptive name\` ` +
          `(e.g. "T3.1 - Add JWT validation to /login"), not a bare "T1"/"T5.5"`,
      );
    }
  }
}

if (problems.length) {
  console.error(`INVALID ${path}:`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
console.log(`OK ${path}`);

/** A name is a placeholder if it's empty, a letter-prefixed sequence number, a bare number, or a generic word. */
function isPlaceholderName(raw) {
  const s = (raw ?? "")
    .trim()
    .replace(/\*\*/g, "")
    .replace(/^\[[ xX]\]\s*/, "")
    .replace(/^\[(?:role|status|severity):[^\]]+\]\s*/i, "")
    .trim();
  if (!s) return true;
  if (/^[A-Za-z]{1,4}\d+(\.\d+)?$/.test(s)) return true; // T1, M3, T5.5, TSK12, C2
  if (/^\d+(\.\d+)?$/.test(s)) return true; // bare number
  if (/^(task|mission|campaign|bug|phase|step|item|untitled|tbd|todo|new\s+\w+)\s*\d*(\.\d+)?$/i.test(s)) return true;
  return false;
}

/** Body text of a `## <label>` section (until the next `## ` heading or the boundary comment). */
function sectionBody(label) {
  const m = new RegExp(`^##\\s+${label}\\s*$`, "m").exec(text);
  if (!m) return "";
  const rest = text.slice(m.index + m[0].length);
  const ends = [rest.search(/^##\s+/m), rest.search(/^<!--/m)].filter((n) => n >= 0);
  return ends.length ? rest.slice(0, Math.min(...ends)) : rest;
}

function hasAcceptanceCriterion() {
  return /^\s*-\s*\[[ xX]\]\s*\S/m.test(sectionBody("Acceptance Criteria"));
}

/** Top-level (column-0) item titles under `## Tasks`. */
function taskNames() {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => /^##\s+Tasks\s*$/.test(l.trim()));
  if (start < 0) return [];
  const out = [];
  for (let i = start + 1; i < lines.length; i++) {
    const raw = lines[i] ?? "";
    if (/^##\s+/.test(raw.trim())) break;
    const m = raw.match(/^(?:\d+[.)]\s+|[-*]\s+)(.*)$/);
    if (m) out.push(m[1] ?? "");
  }
  return out;
}
